=== lamductan/dblacr/files/xsd/Credential.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns="http://www.zurich.ibm.com/security/idemix"
	xmlns:idxcs="http://www.zurich.ibm.com/security/idemix/credentialStructure"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.zurich.ibm.com/security/idemix"
	elementFormDefault="qualified">

	<xs:import
		namespace="http://www.zurich.ibm.com/security/idemix/credentialStructure"
		schemaLocation="CredentialStructure.xsd" />

	<xs:element name="Credential">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Name" type="NonEmptyStringType" minOccurs="0" />
                <xs:sequence minOccurs="0">
                  <xs:element name="SmartcardUid" type="NonEmptyUriType" />
                  <xs:element name="CredentialUidOnSmartcard" type="NonEmptyUriType" />
                </xs:sequence>
				<xs:element name="References" type="ReferencesType" />
				<xs:element name="Attributes" type="AttributesType" />
				<xs:element name="Signature" type="SignatureType" />
				<xs:element name="Features" type="FeaturesType" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="ReferencesType">
		<xs:all>
            <xs:element name="IssuerPublicKey" type="xs:anyURI" />
			<xs:element name="CredentialStructure" type="xs:anyURI" />
		</xs:all>
	</xs:complexType>

	<xs:complexType name="AttributesType">
		<xs:sequence>
			<xs:element name="Attribute" type="AttributeType"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="AttributeType">
		<xs:sequence>
			<xs:choice>
				<xs:element name="Value" type="idxcs:BigIntegerType" />
				<xs:element name="Commitment" type="CommitmentType" />
			</xs:choice>
			<xs:element name="EnumValue" type="NonEmptyStringType"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="name" type="NonEmptyStringType" />
	</xs:complexType>

	<xs:complexType name="CommitmentType">
		<xs:sequence>
			<!-- Commitment -->
			<xs:element name="commitment" type="idxcs:BigIntegerType" />
			<xs:element name="S" type="idxcs:BigIntegerType" />
			<xs:element name="n" type="idxcs:BigIntegerType" />
			<xs:element name="Bases" type="BasesType" />

			<!-- CommitmentOpening -->
			<xs:element name="CommitmentOpening" type="CommitmentOpeningType" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="BasesType">
		<xs:sequence>
			<xs:element name="Base" type="idxcs:BigIntegerType" />
		</xs:sequence>
		<xs:attribute name="num" type="xs:positiveInteger" />
	</xs:complexType>

	<xs:complexType name="CommitmentOpeningType">
		<xs:sequence>
			<xs:element name="Messages" type="MessagesType" />
			<xs:element name="rand" type="idxcs:BigIntegerType" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="MessagesType">
		<xs:sequence>
			<xs:element name="Message" type="idxcs:BigIntegerType" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="SignatureType">
		<xs:sequence>
			<xs:element name="A" type="idxcs:BigIntegerType" />
			<xs:element name="e" type="idxcs:BigIntegerType" />
			<xs:element name="v" type="idxcs:BigIntegerType" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="FeaturesType">
		<xs:sequence>
			<xs:element name="Updates" type="UpdatesType" minOccurs="0"
				maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="UpdatesType">
		<xs:all>
			<xs:element name="UpdateSpecification" type="xs:anyURI" />
			<xs:element name="capU" type="idxcs:BigIntegerType" />
			<xs:element name="vPrime" type="idxcs:BigIntegerType" />
            <xs:element name="nonce" type="idxcs:BigIntegerType" />
            <xs:element name="context" type="idxcs:BigIntegerType" />
		</xs:all>
	</xs:complexType>

	<xs:simpleType name="NonEmptyStringType">
		<xs:restriction base="xs:string">
			<xs:minLength value="1" />
			<xs:whiteSpace value="collapse" />
		</xs:restriction>
	</xs:simpleType>
  
    <xs:simpleType name="NonEmptyUriType">
        <xs:restriction base="xs:anyURI">
            <xs:minLength value="1" />
            <xs:whiteSpace value="collapse" />
        </xs:restriction>
    </xs:simpleType>



</xs:schema>

=== lamductan/dblacr/files/private/Credential_7.xml
<?xml version="1.0" encoding="UTF-8"?><Credential xmlns="http://www.zurich.ibm.com/security/idemix" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.zurich.ibm.com/security/idemix ../xsd/Credential.xsd">
  <References>
    <IssuerPublicKey>http://www.issuer.com/ipk.xml</IssuerPublicKey>
    <CredentialStructure>http://www.ngo.org/CredStruct5.xml</CredentialStructure>
  </References>
  <Attributes>
    <Attribute name="primeEncoding1">
      <Value>3</Value>
      <EnumValue>civilStatus;Marriage</EnumValue>
    </Attribute>
    <Attribute name="primeEncoding2">
      <Value>105</Value>
      <EnumValue>officialLanguage;Italian</EnumValue>
      <EnumValue>officialLanguage;French</EnumValue>
      <EnumValue>officialLanguage;German</EnumValue>
    </Attribute>
  </Attributes>
  <Signature>
    <A>81063680665739176764928283124169782336836700571745903960011928957742708863054965563668042861926761223845085061439286055439390490845876573348494258914866339261598101672892355674572191432440473597988521663104061827861333636467706636456558902076962493667701508563662981671846569369406628464992597887849579310559</A>
    <e>259344723055062059907025491480697571938277889515152306249728583105665800713306759149981690559193987143103445742996990022570975203622723709949927841387654372439802435019310405137437</e>
    <v>2318001132912352108142789560054686343210315463355376132948456018783161471243832014595606185686427645200500002487047397919172635314152970858473805505679431225892673830662874305995744107457307520104844430123516118529988606720758122884061920301152294658295580561676332864730651361135886082226504657740112561001052246833656151282872741285643893326121491796023779244304738691889290228652879319976912710379680506691398114872758334313460</v>
  </Signature>
  <Features/>
</Credential>
