=== lamductan/dblacr/files/xsd/Credential.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns="http://www.zurich.ibm.com/security/idemix"
	xmlns:idxcs="http://www.zurich.ibm.com/security/idemix/credentialStructure"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.zurich.ibm.com/security/idemix"
	elementFormDefault="qualified">

	<xs:import
		namespace="http://www.zurich.ibm.com/security/idemix/credentialStructure"
		schemaLocation="CredentialStructure.xsd" />

	<xs:element name="Credential">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Name" type="NonEmptyStringType" minOccurs="0" />
                <xs:sequence minOccurs="0">
                  <xs:element name="SmartcardUid" type="NonEmptyUriType" />
                  <xs:element name="CredentialUidOnSmartcard" type="NonEmptyUriType" />
                </xs:sequence>
				<xs:element name="References" type="ReferencesType" />
				<xs:element name="Attributes" type="AttributesType" />
				<xs:element name="Signature" type="SignatureType" />
				<xs:element name="Features" type="FeaturesType" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="ReferencesType">
		<xs:all>
            <xs:element name="IssuerPublicKey" type="xs:anyURI" />
			<xs:element name="CredentialStructure" type="xs:anyURI" />
		</xs:all>
	</xs:complexType>

	<xs:complexType name="AttributesType">
		<xs:sequence>
			<xs:element name="Attribute" type="AttributeType"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="AttributeType">
		<xs:sequence>
			<xs:choice>
				<xs:element name="Value" type="idxcs:BigIntegerType" />
				<xs:element name="Commitment" type="CommitmentType" />
			</xs:choice>
			<xs:element name="EnumValue" type="NonEmptyStringType"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="name" type="NonEmptyStringType" />
	</xs:complexType>

	<xs:complexType name="CommitmentType">
		<xs:sequence>
			<!-- Commitment -->
			<xs:element name="commitment" type="idxcs:BigIntegerType" />
			<xs:element name="S" type="idxcs:BigIntegerType" />
			<xs:element name="n" type="idxcs:BigIntegerType" />
			<xs:element name="Bases" type="BasesType" />

			<!-- CommitmentOpening -->
			<xs:element name="CommitmentOpening" type="CommitmentOpeningType" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="BasesType">
		<xs:sequence>
			<xs:element name="Base" type="idxcs:BigIntegerType" />
		</xs:sequence>
		<xs:attribute name="num" type="xs:positiveInteger" />
	</xs:complexType>

	<xs:complexType name="CommitmentOpeningType">
		<xs:sequence>
			<xs:element name="Messages" type="MessagesType" />
			<xs:element name="rand" type="idxcs:BigIntegerType" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="MessagesType">
		<xs:sequence>
			<xs:element name="Message" type="idxcs:BigIntegerType" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="SignatureType">
		<xs:sequence>
			<xs:element name="A" type="idxcs:BigIntegerType" />
			<xs:element name="e" type="idxcs:BigIntegerType" />
			<xs:element name="v" type="idxcs:BigIntegerType" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="FeaturesType">
		<xs:sequence>
			<xs:element name="Updates" type="UpdatesType" minOccurs="0"
				maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="UpdatesType">
		<xs:all>
			<xs:element name="UpdateSpecification" type="xs:anyURI" />
			<xs:element name="capU" type="idxcs:BigIntegerType" />
			<xs:element name="vPrime" type="idxcs:BigIntegerType" />
            <xs:element name="nonce" type="idxcs:BigIntegerType" />
            <xs:element name="context" type="idxcs:BigIntegerType" />
		</xs:all>
	</xs:complexType>

	<xs:simpleType name="NonEmptyStringType">
		<xs:restriction base="xs:string">
			<xs:minLength value="1" />
			<xs:whiteSpace value="collapse" />
		</xs:restriction>
	</xs:simpleType>
  
    <xs:simpleType name="NonEmptyUriType">
        <xs:restriction base="xs:anyURI">
            <xs:minLength value="1" />
            <xs:whiteSpace value="collapse" />
        </xs:restriction>
    </xs:simpleType>



</xs:schema>

=== lamductan/dblacr/files/private/Credential_1b.xml
<?xml version="1.0" encoding="UTF-8"?><Credential xmlns="http://www.zurich.ibm.com/security/idemix" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.zurich.ibm.com/security/idemix ../xsd/Credential.xsd">
  <References>
    <IssuerPublicKey>http://www.issuer.com/ipk.xml</IssuerPublicKey>
    <CredentialStructure>http://www.ngo.org/CredStruct1b.xml</CredentialStructure>
  </References>
  <Attributes>
    <Attribute name="attr1">
      <Value>1313</Value>
    </Attribute>
    <Attribute name="attr2">
      <Value>1314</Value>
    </Attribute>
    <Attribute name="attr3">
      <Value>1315</Value>
    </Attribute>
    <Attribute name="attr4">
      <Value>4243</Value>
    </Attribute>
  </Attributes>
  <Signature>
    <A>38547885244920408785316177865629434199365967665496159822167562362705158812565467840098716303563206424452956037679549092895646124822196667516031538122413463188187237751148452743625031889263143909916968571194593125477112301398826290727643747133439251267729254167274540569453407612727207280897936437260509766964</A>
    <e>259344723055062059907025491480697571938277889515152306249728583105665800713306759149981690559193987143031743958363312210535470354979367218132856546485268278382025045733377278057489</e>
    <v>2086209402480643388505245372123173425252975461480642729527099994670633243771451107501447203184297355401858531972751239800919756320151124884464156191757262460584267827223872134858261701184565115148684891409168388374747172315932824546325024385675342040268231977956527253037244576750856402465980178255119378262931027437646200147986757090791162689374644613025667446387072006422498338165911474662114109966877586485632489131183566965975</v>
  </Signature>
  <Features/>
</Credential>

=== lamductan/dblacr/files/private/Credential_8.xml
<?xml version="1.0" encoding="UTF-8"?><Credential xmlns="http://www.zurich.ibm.com/security/idemix" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.zurich.ibm.com/security/idemix ../xsd/Credential.xsd">
  <References>
    <IssuerPublicKey>http://www.issuer.com/ipk.xml</IssuerPublicKey>
    <CredentialStructure>http://www.ngo.org/CredStruct6.xml</CredentialStructure>
  </References>
  <Attributes>
    <Attribute name="primeEncoding1">
      <Value>20550799</Value>
      <EnumValue>officialLanguage;Italian</EnumValue>
      <EnumValue>civilStatus;Common-lawPartner</EnumValue>
      <EnumValue>officialLanguage;Rhaeto-Romanic</EnumValue>
      <EnumValue>sex;Male</EnumValue>
      <EnumValue>officialLanguage;German</EnumValue>
    </Attribute>
    <Attribute name="primeEncoding2">
      <Commitment>
        <commitment>118501625669290620506257060871879848651914846327174328280772687909272285486118557565016573443708684374218341774042099888917406065751116158571245576170977428482669179847464185106623690142724878609071216964597717303926484481384537950402339890577313414822502962049297124471980414293618777189371496522786671560466</commitment>
        <S>67254978546586387746371812310799963199648525605698331029534251596232370027172664240407979301953626203319151762261652600759005672320154674443879786091477200196732310064009956256955600787213240490631750504640542741919004918195148381937131971214494976707809949834888578482370086318215794644835662415992756882603</S>
        <n>119044022186753690018430516777857594963368506134570973357311270757022475907431866561996530390008551579472891604827125833721397252053305134571142913793132219807152566643909997919585593336578843205692900329154693554897764568744373060642870170977183333982530812867790710426944978612698155788787287562342569509073</n>
        <Bases num="1">
          <Base>32921814524377017041931913576584439560632569931404502353475383371878236583978512140794089573553532245705459408417869416443659319693175867098884370978448886092451288399260225788087061330501562228689833809787781336214456117869525090072024003349054898349464658701210662766987336518999452802422749574128824579840</Base>
        </Bases>
        <CommitmentOpening>
          <Messages>
            <Message>129271155</Message>
          </Messages>
          <rand>27817636250359651442715077898297770061646860588881948544628239302822282187846411513973609862987452473391708176154253593642846938073399782545028943905842645069516856265737473458916499521562017851595595463519873060463927271077089691960121403939001747219602610681807829624417189734782374041440767263795177074423</rand>
        </CommitmentOpening>
      </Commitment>
      <EnumValue>driverCategory;D1E</EnumValue>
      <EnumValue>driverCategory;C1</EnumValue>
      <EnumValue>driverCategory;D1</EnumValue>
      <EnumValue>driverCategory;B</EnumValue>
      <EnumValue>driverCategory;A1</EnumValue>
      <EnumValue>driverCategory;C1E</EnumValue>
      <EnumValue>driverCategory;BE</EnumValue>
    </Attribute>
  </Attributes>
  <Signature>
    <A>78175799822632960818606191482908262158553650952983663832584326422725392623257850564434653701840437837183024873654878894243476147004368122865093811817079043763263618247295969282036432884313976812172565704932512049243968717493652080040719910167919954369849223714934908562211271713112852999633930312854381122885</A>
    <e>259344723055062059907025491480697571938277889515152306249728583105665800713306759149981690559193987143041911644143230013088949509839870267458761015589979911811377597076958298141849</e>
    <v>3255075302850792558971335976168645687888872024035996138736526957509336099258349827965650268140528083384127053476594390261160872125403858413746378864806399740420418071616084449581806800255404529472888275516734726265106234203864482834439988152609445956161767205784076187174806361842890849725647496365712027253809260862142524782586009638757437615792512837413711901900186424686574523672702665639631452102325924261177519817931181885667</v>
  </Signature>
  <Features/>
</Credential>

=== lamductan/dblacr/files/private/Credential_complete.xml
<?xml version="1.0" encoding="UTF-8"?><Credential xmlns="http://www.zurich.ibm.com/security/idemix" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.zurich.ibm.com/security/idemix ../xsd/Credential.xsd">
  <References>
    <IssuerPublicKey>http://www.ch.ch/identityCard/v2012/ipk.xml</IssuerPublicKey>
    <CredentialStructure>http://www.ch.ch/identityCard/v2012/CredStructComplete.xml</CredentialStructure>
  </References>
  <Attributes>
    <Attribute name="FirstName">
      <Value>-688801371937649959579820756394775575840715893149737780334536265877869334605</Value>
    </Attribute>
    <Attribute name="LastName">
      <Value>-21845598845916938605275525313893548943236279141879078706962526334797938325724</Value>
    </Attribute>
    <Attribute name="SocialSecurityNumber">
      <Value>1313</Value>
    </Attribute>
    <Attribute name="BirthDate">
      <Value>1314</Value>
    </Attribute>
    <Attribute name="Diet">
      <Commitment>
        <commitment>96664811441283025187676609642640575030759019480955012035645059201138521431449916741676451269794150318901390447514841033667607151994105229511166872605803633036206918252472517547667094562205780633535535804208894030043915018047205477365868663999316586121305252276364090168910502691262150266791536012760683319379</commitment>
        <S>67254978546586387746371812310799963199648525605698331029534251596232370027172664240407979301953626203319151762261652600759005672320154674443879786091477200196732310064009956256955600787213240490631750504640542741919004918195148381937131971214494976707809949834888578482370086318215794644835662415992756882603</S>
        <n>119044022186753690018430516777857594963368506134570973357311270757022475907431866561996530390008551579472891604827125833721397252053305134571142913793132219807152566643909997919585593336578843205692900329154693554897764568744373060642870170977183333982530812867790710426944978612698155788787287562342569509073</n>
        <Bases num="1">
          <Base>32921814524377017041931913576584439560632569931404502353475383371878236583978512140794089573553532245705459408417869416443659319693175867098884370978448886092451288399260225788087061330501562228689833809787781336214456117869525090072024003349054898349464658701210662766987336518999452802422749574128824579840</Base>
        </Bases>
        <CommitmentOpening>
          <Messages>
            <Message>-27504312941977732075957586170872727553942019300228568380937261894832069870739</Message>
          </Messages>
          <rand>2944447706759055407566015056190404238540416281568439471108296937010069218751737405869656896516211134372921130281104843630650926261346802744627996307532320989896010483125021613920166264677434688374665447324274367946325008434885228509735191471971337078856504678594060488137157330955569549860201117815296742588</rand>
        </CommitmentOpening>
      </Commitment>
    </Attribute>
    <Attribute name="Epoch">
      <Value>3185</Value>
    </Attribute>
    <Attribute name="PrimeEncoding1">
      <Value>17917</Value>
      <EnumValue>OfficialLanguage;German</EnumValue>
      <EnumValue>CivilStatus;Common-lawPartner</EnumValue>
      <EnumValue>Gender;Male</EnumValue>
    </Attribute>
    <Attribute name="PrimeEncoding2">
      <Commitment>
        <commitment>118661833384529302930958718921627037754202876780291281939182913540890026002742427410226434254046242155055787689157200537794460840172537616441721944948333290807497709175702679841843586211696987324300251000816000948874833279294090200204465178432670167792304018578505914198402893729111847307212879838679108440706</commitment>
        <S>67254978546586387746371812310799963199648525605698331029534251596232370027172664240407979301953626203319151762261652600759005672320154674443879786091477200196732310064009956256955600787213240490631750504640542741919004918195148381937131971214494976707809949834888578482370086318215794644835662415992756882603</S>
        <n>119044022186753690018430516777857594963368506134570973357311270757022475907431866561996530390008551579472891604827125833721397252053305134571142913793132219807152566643909997919585593336578843205692900329154693554897764568744373060642870170977183333982530812867790710426944978612698155788787287562342569509073</n>
        <Bases num="1">
          <Base>32921814524377017041931913576584439560632569931404502353475383371878236583978512140794089573553532245705459408417869416443659319693175867098884370978448886092451288399260225788087061330501562228689833809787781336214456117869525090072024003349054898349464658701210662766987336518999452802422749574128824579840</Base>
        </Bases>
        <CommitmentOpening>
          <Messages>
            <Message>701054585</Message>
          </Messages>
          <rand>8652629355378491624613937029832254292005409940991589696331853967293952031133548481368865013689035004018063939131612098700150740137560588549501967550991782276188778415569106524849726117596602570852309332544662931697657425637389210449093398920686228346726253292494704019259301441303929410537658968747877355570</rand>
        </CommitmentOpening>
      </Commitment>
      <EnumValue>DriverCategory;F</EnumValue>
      <EnumValue>DriverCategory;B1</EnumValue>
      <EnumValue>DriverCategory;G</EnumValue>
      <EnumValue>DriverCategory;M</EnumValue>
      <EnumValue>DriverCategory;B</EnumValue>
      <EnumValue>DriverCategory;C</EnumValue>
      <EnumValue>DriverCategory;D</EnumValue>
    </Attribute>
  </Attributes>
  <Signature>
    <A>8078538325901340852381841532453288818658805679421367925551600197460225767033557589365460380012958848253520814995974526358781258550655783367918177436547300337086661507032282440627681354217413380772189578805708330064808194851797098137968525997218617265216449004535265992073622299774018412672179014886206889660</A>
    <e>259344723055062059907025491480697571938277889515152306249728583105665800713306759149981690559193987143081559857308200741484184131430688452505339959514830127850553220350087939062947</e>
    <v>2218912854148810264456598746976110124583217641671696445951441753390942817136344102198225032621684179914931962439962844541574518510159837300987888492694960343863894537518942747578029270685732154561117143514083255933488140196353194879459236419113564151823328587554375670580376964641959491761807347647388783883898383707241973544774302292000536518465054774508405691161588254296801894867694491070468090992546940464178062674036631482056</v>
  </Signature>
  <Features>
    <Updates>
      <UpdateSpecification>http://www.base.of.uri/where/the/updates/will/be/Update_r61umup0q7phhqc9vps.xml</UpdateSpecification>
      <capU>98351979528710957753507469530105885546554703788955714136232836214696034531872335469777032944631818336788697926121709664661376772880879487020241926933830155503201147043826823077976833430117107610499809622483603804401181587288372512326216345275086688318959337422136441240031078133537844487102245120112762270702</capU>
      <vPrime>458564961355590357487296381333320966302462853410710471835219414263463441534862878040643953598932779195343020404424802101476114494049061873143986827762750894634299161002810943874956218814392486457415021454423170022618284897292672690282118452519411235583978353675199791780403864065997387670434319293527277586057285074917782684789932</vPrime>
      <nonce>1101766145695401681539</nonce>
      <context>57132007859431325469155257180381990227612921134850039113478974728701260469495</context>
    </Updates>
  </Features>
</Credential>

=== lamductan/dblacr/files/private/Credential_0.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Credential xmlns="http://www.zurich.ibm.com/security/idemix" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.zurich.ibm.com/security/idemix ../xsd/Credential.xsd">
  <References>
    <IssuerPublicKey>http://www.issuer.com/ipk.xml</IssuerPublicKey>
    <CredentialStructure>http://www.ngo.org/CredStruct0.xml</CredentialStructure>
  </References>
  <Attributes/>
  <Signature>
    <A>21397845173032322715316801857580527660525153118887156537686888836670052750511347181937085496857762535091872366938631126944680978666173717760682752416257484052645265872895662285876494806327307780024781464567685948404719381827936069015123847634453227907084793616951390602215721319879411494096395138010534092755</A>
    <e>259344723055062059907025491480697571938277889515152306249728583105665800713306759149981690559193987143046676326919481317594417490678113170143315256239006926475310450001483072307279</e>
    <v>2059229659712534633327076997714248185756791674572990540821479274021565608509026222539620467702385543364304990762431040546918335476034137190242968355463379967425369784382295173671401097868734126280961700656872913628340089061116571620435985132827078559170377688788611634397901428421782782743831221049627028055193737568885829028948473617502640721674252848477428346067698402440964781210515757541342598610386673175658258644922556170875</v>
  </Signature>
  <Features/>
</Credential>

=== lamductan/dblacr/files/private/Credential_5.xml
<?xml version="1.0" encoding="UTF-8"?><Credential xmlns="http://www.zurich.ibm.com/security/idemix" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.zurich.ibm.com/security/idemix ../xsd/Credential.xsd">
  <References>
    <IssuerPublicKey>http://www.issuer.com/ipk.xml</IssuerPublicKey>
    <CredentialStructure>http://www.ngo.org/CredStruct3.xml</CredentialStructure>
  </References>
  <Attributes>
    <Attribute name="attr1">
      <Value>1313</Value>
    </Attribute>
    <Attribute name="attr2">
      <Value>1315</Value>
    </Attribute>
    <Attribute name="attr3">
      <Commitment>
        <commitment>109662950371899881719023623576111417062995685578512576240355277756031173397453361032757612466931478435486484028560280181158999850937219043857826539869141831998252939026291125391056204317543307276757887742535357645332697302685543557897128308391743713111011714672140871232626567025539769872464194834455102969888</commitment>
        <S>67254978546586387746371812310799963199648525605698331029534251596232370027172664240407979301953626203319151762261652600759005672320154674443879786091477200196732310064009956256955600787213240490631750504640542741919004918195148381937131971214494976707809949834888578482370086318215794644835662415992756882603</S>
        <n>119044022186753690018430516777857594963368506134570973357311270757022475907431866561996530390008551579472891604827125833721397252053305134571142913793132219807152566643909997919585593336578843205692900329154693554897764568744373060642870170977183333982530812867790710426944978612698155788787287562342569509073</n>
        <Bases num="1">
          <Base>32921814524377017041931913576584439560632569931404502353475383371878236583978512140794089573553532245705459408417869416443659319693175867098884370978448886092451288399260225788087061330501562228689833809787781336214456117869525090072024003349054898349464658701210662766987336518999452802422749574128824579840</Base>
        </Bases>
        <CommitmentOpening>
          <Messages>
            <Message>1318</Message>
          </Messages>
          <rand>15855610395663705894320940319993853988065547656763879141421570854170817569596417828782399686351025645478304041100597684093593873611384503570394799056721212039519876935186226334611461384873179099176656004546040717330599010169469876859914098155541780401614200734327798683682595298794131659394529735259868785879</rand>
        </CommitmentOpening>
      </Commitment>
    </Attribute>
  </Attributes>
  <Signature>
    <A>24796957393598574770958651336527416245511376175201752026652177705086191010275496512275029198207260216521152377580876201185813216049769769985586032689962727798335351036752529545731717606845822233948468675643673154195569145259591696079059770126215157306420085035914897984510109581331354648616141815166704658744</A>
    <e>259344723055062059907025491480697571938277889515152306249728583105665800713306759149981690559193987143085885780205174975926193169051176876576082199061907986223344387012111457124513</e>
    <v>2268747689816799471088627480127415687632049080350222288059651231536862697848712889718841433249101701856460303162369206042728458054252343552069615785278581996855635626966268471111939365634209451835300021339396769838320154469577487605714460440052200626188850792150758017415934465514959981038805768591044389710794879098118905599523885315649174844491696427215703996102771393256483365274069193411086581815761289964796330600360007422622</v>
  </Signature>
  <Features/>
</Credential>

=== lamductan/dblacr/files/private/Credential_1c.xml
<?xml version="1.0" encoding="UTF-8"?><Credential xmlns="http://www.zurich.ibm.com/security/idemix" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.zurich.ibm.com/security/idemix ../xsd/Credential.xsd">
  <References>
    <IssuerPublicKey>http://www.issuer.com/ipk.xml</IssuerPublicKey>
    <CredentialStructure>http://www.ngo.org/CredStruct1c.xml</CredentialStructure>
  </References>
  <Attributes>
    <Attribute name="attr1">
      <Value>1313</Value>
    </Attribute>
    <Attribute name="attr2">
      <Value>1314</Value>
    </Attribute>
    <Attribute name="attr3">
      <Value>3650481942402582375958668357344705576112980177137059879763127269205158951849</Value>
    </Attribute>
    <Attribute name="attr4">
      <Value>102787220464222280996129743007714452389327536866272886834038024772423502010111</Value>
    </Attribute>
  </Attributes>
  <Signature>
    <A>4577203370457028103328464524009908407678530932702268969604921740432094012057267265391467549098938756160113921075018338429871253984616919712553244267534453860570061726743969128237710056258666612030637074181673648718547405470833959238541335822229329923258603946007812460664815016752977751870583672112219685670</A>
    <e>259344723055062059907025491480697571938277889515152306249728583105665800713306759149981690559193987143066508365305231362110587327836295793570784667053393280624077323010434407507031</e>
    <v>1886712313377576902346742514526196255042662312355169165251575149544895673976790723668240852236092150258573397512218034802547632226657789411045047235570833503074786239001345192071113059146559077737251881861602343246597598194456589149108602164508317919280780656546557145721654584626247702048639106763750468019683560611741773821931085497601700798100259059092621784596870472909399759968010607601519304713480261249645912652372855635295</v>
  </Signature>
  <Features>
    <Updates>
      <UpdateSpecification>http://www.base.of.uri/where/the/updates/will/be/Update_gji0mel50hajioefprj4.xml</UpdateSpecification>
      <capU>39795474969593217416933349962463427292420963711509523012644375556667003367544744347604703363119433727381127286693620204196970892718137808366083096595650221410120190651925997145831053114343242093092131546774973177240317249450118504971328898214680296777428034974303889048742870352654763091521947240404812714441</capU>
      <vPrime>784323090155700429083358475107418501456204408507084599427340724518962109232946679604573793795796227703476037952378296757102089545258163392407723085635724420980131397140169296555394807787367629535017480648768175136189982752076226969716669107564898104126800227594154544021604587532558119604695739584139157256577274345742785085296990</vPrime>
      <nonce>481722685390562291726</nonce>
      <context>57132007859431325469155257180381990227612921134850039113478974728701260469495</context>
    </Updates>
  </Features>
</Credential>

=== lamductan/dblacr/files/private/Credential_Enum_AdvIss.xml
<?xml version="1.0" encoding="UTF-8"?><Credential xmlns="http://www.zurich.ibm.com/security/idemix" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.zurich.ibm.com/security/idemix ../xsd/Credential.xsd">
  <References>
    <IssuerPublicKey>http://www.issuer.com/ipk.xml</IssuerPublicKey>
    <CredentialStructure>http://www.ngo.org/CredStruct7.xml</CredentialStructure>
  </References>
  <Attributes>
    <Attribute name="peCivilStatus">
      <Value>19</Value>
      <EnumValue>civilStatus;Common-lawPartner</EnumValue>
    </Attribute>
    <Attribute name="peOfficialLanguage">
      <Value>26381</Value>
      <EnumValue>officialLanguage;Italian</EnumValue>
      <EnumValue>officialLanguage;Rhaeto-Romanic</EnumValue>
      <EnumValue>officialLanguage;German</EnumValue>
    </Attribute>
    <Attribute name="peDriverCategory">
      <Value>129271155</Value>
      <EnumValue>driverCategory;D1E</EnumValue>
      <EnumValue>driverCategory;C1</EnumValue>
      <EnumValue>driverCategory;D1</EnumValue>
      <EnumValue>driverCategory;B</EnumValue>
      <EnumValue>driverCategory;A1</EnumValue>
      <EnumValue>driverCategory;C1E</EnumValue>
      <EnumValue>driverCategory;BE</EnumValue>
    </Attribute>
    <Attribute name="peSex">
      <Value>41</Value>
      <EnumValue>sex;Male</EnumValue>
    </Attribute>
  </Attributes>
  <Signature>
    <A>2898490956978725349674873550602321465739623643733799139219143556475521091833287322991715658132263996022308550938366788709610377628421873363382479508032081926385943314957229482440841971786241077379081233094587901859809659874058456974230381251107425822875825547846510594718687325149999921042776293449762470251</A>
    <e>259344723055062059907025491480697571938277889515152306249728583105665800713306759149981690559193987143073374528172748214790523485995597054708545643961025945876975002493408488709107</e>
    <v>-333518544360929587209902029518028488310063405155252075782012436540640187529503994318530229916467584936667206682463288900553982793703158036424226481994874336362883796663473207103643774151716653803816931134200585826848407883483829773286941343621761577103151977840263453447922664482523275302712148769854616930118897034315065135790424802016117045553576790424030995612270673672700998886797114775858586423064556937566714217500907806572</v>
  </Signature>
  <Features/>
</Credential>
