=== lamductan/dblacr/files/xsd/CredentialStructure.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema
	xmlns="http://www.zurich.ibm.com/security/idemix/credentialStructure"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.zurich.ibm.com/security/idemix/credentialStructure"
	elementFormDefault="qualified">

	<xs:element name="CredentialStructure">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="References" type="ReferencesType" minOccurs="0"/>
				<xs:element name="Attributes" type="AttributesType" />
				<xs:element name="Features" type="FeaturesType" />
				<xs:element name="Implementation" type="ImplementationType" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="ReferencesType">
		<xs:all>
			<xs:element name="IssuerPublicKey" type="xs:anyURI" />
		</xs:all>
	</xs:complexType>

	<xs:complexType name="AttributesType">
		<xs:sequence>
			<xs:element name="Attribute" type="AttributeType"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="AttributeType">
		<xs:sequence>
			<xs:element name="EnumValue" type="NonEmptyStringType"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="issuanceMode" type="issuanceModeType" />
		<xs:attribute name="name" type="NonEmptyStringType" />
		<xs:attribute name="type" type="dataType" />
	</xs:complexType>

	<xs:simpleType name="NonEmptyStringType">
		<xs:restriction base="xs:string">
			<xs:minLength value="1" />
			<xs:whiteSpace value="collapse" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="issuanceModeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="known" />
			<xs:enumeration value="committed" />
			<xs:enumeration value="hidden" />
            <xs:enumeration value="issuer" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="dataType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="int" />
			<xs:enumeration value="string" />
			<xs:enumeration value="epoch" />
			<xs:enumeration value="enum" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="FeaturesType">
		<xs:sequence>
            <xs:element name="OnSmartcard" type="xs:boolean" default="false" minOccurs="0" />
			<xs:element name="UpdateSpecification" type="xs:anyURI" minOccurs="0"
				maxOccurs="1" />
            <xs:element name="Epoch" type="xs:anySimpleType" minOccurs="0"
                maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ImplementationType">
		<xs:sequence>
			<xs:element name="PrimeEncoding" type="PrimeEncodingType"
				minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="AttributeOrder" type="AttributeOrderType" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="PrimeEncodingType">
		<xs:sequence>
			<xs:element name="PrimeFactor" type="PrimeFactorType"
				minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="name" type="NonEmptyStringType" />
        <xs:attribute name="numValues" type="xs:int" />
	</xs:complexType>

	<xs:complexType name="PrimeFactorType">
		<xs:simpleContent>
			<xs:extension base="BigIntegerType">
				<xs:attribute name="attName" type="NonEmptyStringType" />
				<xs:attribute name="attValue" type="NonEmptyStringType" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:simpleType name="BigIntegerType">
		<xs:restriction base="xs:string">
			<xs:whiteSpace value="collapse" />
			<xs:pattern value="-?[0-9]+" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="AttributeOrderType">
		<xs:sequence>
			<xs:element name="Attribute" type="SimpleAttributeType"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="SimpleAttributeType">
		<xs:simpleContent>
			<xs:extension base="xs:positiveInteger">
				<xs:attribute name="name" type="NonEmptyStringType" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

</xs:schema>

=== lamductan/dblacr/files/issuerData/CredStructComplete.xml
<?xml version="1.0" encoding="UTF-8"?>
<CredentialStructure xmlns="http://www.zurich.ibm.com/security/idemix/credentialStructure"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xsi:schemaLocation="http://www.zurich.ibm.com/security/idemix/credentialStructure ../xsd/CredentialStructure.xsd">

	<Attributes>
		<Attribute issuanceMode="known" name="FirstName" type="string" />
		<Attribute issuanceMode="known" name="LastName" type="string" />
		<Attribute issuanceMode="known" name="CivilStatus" type="enum">
			<EnumValue>Marriage</EnumValue>
			<EnumValue>NeverMarried</EnumValue>
			<EnumValue>Widowed</EnumValue>
			<EnumValue>LegallySeparated</EnumValue>
			<EnumValue>AnnulledMarriage</EnumValue>
			<EnumValue>Divorced</EnumValue>
			<EnumValue>Common-lawPartner</EnumValue>
		</Attribute>
		<Attribute issuanceMode="known" name="SocialSecurityNumber"
			type="int" />
		<Attribute issuanceMode="known" name="BirthDate" type="int" />
		<Attribute issuanceMode="committed" name="Diet" type="string" />
		<Attribute issuanceMode="known" name="Epoch" type="epoch" />
		<Attribute issuanceMode="known" name="OfficialLanguage"
			type="enum">
			<EnumValue>German</EnumValue>
			<EnumValue>French</EnumValue>
			<EnumValue>Italian</EnumValue>
			<EnumValue>Rhaeto-Romanic</EnumValue>
		</Attribute>
		<Attribute issuanceMode="committed" name="DriverCategory"
			type="enum">
			<EnumValue>A1</EnumValue>
			<EnumValue>B</EnumValue>
			<EnumValue>B1</EnumValue>
			<EnumValue>C</EnumValue>
			<EnumValue>C1</EnumValue>
			<EnumValue>D</EnumValue>
			<EnumValue>D1</EnumValue>
			<EnumValue>BE</EnumValue>
			<EnumValue>CE</EnumValue>
			<EnumValue>DE</EnumValue>
			<EnumValue>C1E</EnumValue>
			<EnumValue>D1E</EnumValue>
			<EnumValue>F</EnumValue>
			<EnumValue>G</EnumValue>
			<EnumValue>M</EnumValue>
		</Attribute>
		<Attribute issuanceMode="known" name="Gender" type="enum">
			<EnumValue>Male</EnumValue>
			<EnumValue>Female</EnumValue>
		</Attribute>
	</Attributes>

	<Features>
		<UpdateSpecification>http://www.ch.ch/identityCard/v2012/updateSpecification_CredStructComplete.xml
		</UpdateSpecification>
	</Features>

	<Implementation>
		<PrimeEncoding name="PrimeEncoding1" numValues="15">
			<PrimeFactor attName="CivilStatus" attValue="Marriage">3
			</PrimeFactor>
			<PrimeFactor attName="CivilStatus" attValue="NeverMarried">5
			</PrimeFactor>
			<PrimeFactor attName="CivilStatus" attValue="Widowed">7
			</PrimeFactor>
			<PrimeFactor attName="CivilStatus" attValue="LegallySeparated">11
			</PrimeFactor>
			<PrimeFactor attName="CivilStatus" attValue="AnnulledMarriage">13
			</PrimeFactor>
			<PrimeFactor attName="CivilStatus" attValue="Divorced">17
			</PrimeFactor>
			<PrimeFactor attName="CivilStatus" attValue="Common-lawPartner">19
			</PrimeFactor>
			<PrimeFactor attName="OfficialLanguage" attValue="German">23
			</PrimeFactor>
			<PrimeFactor attName="OfficialLanguage" attValue="French">29
			</PrimeFactor>
			<PrimeFactor attName="OfficialLanguage" attValue="Italian">31
			</PrimeFactor>
			<PrimeFactor attName="OfficialLanguage" attValue="Rhaeto-Romanic">37
			</PrimeFactor>
			<PrimeFactor attName="Gender" attValue="Male">41
			</PrimeFactor>
			<PrimeFactor attName="Gender" attValue="Female">43
			</PrimeFactor>
		</PrimeEncoding>
		<PrimeEncoding name="PrimeEncoding2" numValues="15">
			<PrimeFactor attName="DriverCategory" attValue="A1">3
			</PrimeFactor>
			<PrimeFactor attName="DriverCategory" attValue="B">5
			</PrimeFactor>
			<PrimeFactor attName="DriverCategory" attValue="B1">7
			</PrimeFactor>
			<PrimeFactor attName="DriverCategory" attValue="C">11
			</PrimeFactor>
			<PrimeFactor attName="DriverCategory" attValue="C1">13
			</PrimeFactor>
			<PrimeFactor attName="DriverCategory" attValue="D">17
			</PrimeFactor>
			<PrimeFactor attName="DriverCategory" attValue="D1">19
			</PrimeFactor>
			<PrimeFactor attName="DriverCategory" attValue="BE">23
			</PrimeFactor>
			<PrimeFactor attName="DriverCategory" attValue="CE">29
			</PrimeFactor>
			<PrimeFactor attName="DriverCategory" attValue="DE">31
			</PrimeFactor>
			<PrimeFactor attName="DriverCategory" attValue="C1E">37
			</PrimeFactor>
			<PrimeFactor attName="DriverCategory" attValue="D1E">41
			</PrimeFactor>
			<PrimeFactor attName="DriverCategory" attValue="F">43
			</PrimeFactor>
			<PrimeFactor attName="DriverCategory" attValue="G">47
			</PrimeFactor>
			<PrimeFactor attName="DriverCategory" attValue="M">53
			</PrimeFactor>
		</PrimeEncoding>
		<AttributeOrder>
			<Attribute name="FirstName">1</Attribute>
			<Attribute name="LastName">2</Attribute>
			<Attribute name="PrimeEncoding1">3</Attribute>
			<Attribute name="SocialSecurityNumber">4</Attribute>
			<Attribute name="BirthDate">5</Attribute>
			<Attribute name="Diet">6</Attribute>
			<Attribute name="Epoch">7</Attribute>
			<Attribute name="PrimeEncoding2">8</Attribute>
		</AttributeOrder>
	</Implementation>

</CredentialStructure>

=== lamductan/dblacr/files/issuerData/CredStruct1d.xml
<?xml version="1.0" encoding="UTF-8"?>
<CredentialStructure xmlns="http://www.zurich.ibm.com/security/idemix/credentialStructure"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xsi:schemaLocation="http://www.zurich.ibm.com/security/idemix/credentialStructure ../xsd/CredentialStructure.xsd">

	<Attributes>
		<Attribute issuanceMode="hidden" name="attr1" type="int" />
		<Attribute issuanceMode="hidden" name="attr2" type="string" />
		<Attribute issuanceMode="hidden" name="attr3" type="int" />
		<Attribute issuanceMode="known" name="attr4" type="epoch" />
	</Attributes>

	<Features>
		<UpdateSpecification>http://www.issuer.com/updateSpecification_CredStruct1d.xml
		</UpdateSpecification>
	</Features>

	<Implementation>
		<AttributeOrder>
			<Attribute name="attr1">1</Attribute>
			<Attribute name="attr2">2</Attribute>
			<Attribute name="attr3">3</Attribute>
			<Attribute name="attr4">4</Attribute>
		</AttributeOrder>
	</Implementation>

</CredentialStructure>

=== lamductan/dblacr/files/issuerData/CredStructWithSmartcardNoUser.xml
<?xml version="1.0" encoding="UTF-8"?>
<CredentialStructure xmlns="http://www.zurich.ibm.com/security/idemix/credentialStructure"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xsi:schemaLocation="http://www.zurich.ibm.com/security/idemix/credentialStructure ../xsd/CredentialStructure.xsd">
    
    <Attributes>
        <Attribute issuanceMode="issuer" name="attr1" type="int" />
        <Attribute issuanceMode="issuer" name="attr2" type="int" />
        <Attribute issuanceMode="issuer" name="attr3" type="int" />
        <Attribute issuanceMode="issuer" name="attr4" type="int" />
        <Attribute issuanceMode="issuer" name="attr5" type="int" />
        <Attribute issuanceMode="issuer" name="attr6" type="int" />
    </Attributes>

    <Features>
      <OnSmartcard>true</OnSmartcard>
    </Features>

    <Implementation>
        <AttributeOrder>
            <Attribute name="attr1">1</Attribute>
            <Attribute name="attr2">2</Attribute>
            <Attribute name="attr3">3</Attribute>
            <Attribute name="attr4">4</Attribute>
            <Attribute name="attr5">5</Attribute>
            <Attribute name="attr6">6</Attribute>
        </AttributeOrder>
    </Implementation>

</CredentialStructure>

=== lamductan/dblacr/files/issuerData/CredStruct_UtopiaHiddenValues.xml
<?xml version="1.0" encoding="UTF-8"?>
<CredentialStructure xmlns="http://www.zurich.ibm.com/security/idemix/credentialStructure"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xsi:schemaLocation="http://www.zurich.ibm.com/security/idemix/credentialStructure ../xsd/CredentialStructure.xsd">

	<References>
		<IssuerPublicKey>http://www.zurich.ibm.com/~pbi/idmx_2-3/utopia/ipk.xml</IssuerPublicKey>
	</References>

	<Attributes>
		<Attribute issuanceMode="hidden" name="firstName" type="string" />
		<Attribute issuanceMode="hidden" name="lastName" type="string" />
		<Attribute issuanceMode="hidden" name="dateOfBirth" type="int" />
	</Attributes>

	<Features />

	<Implementation>
		<AttributeOrder>
			<Attribute name="firstName">1</Attribute>
			<Attribute name="lastName">2</Attribute>
			<Attribute name="dateOfBirth">3</Attribute>
		</AttributeOrder>
	</Implementation>

</CredentialStructure>

=== lamductan/dblacr/files/issuerData/CredStruct7.xml
<?xml version="1.0" encoding="UTF-8"?>
<CredentialStructure xmlns="http://www.zurich.ibm.com/security/idemix/credentialStructure"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xsi:schemaLocation="http://www.zurich.ibm.com/security/idemix/credentialStructure ../xsd/CredentialStructure.xsd">

	<References>
		<IssuerPublicKey>
			http://www.zurich.ibm.com/security/idmx/v2/testIssuer/ipk.xml
		</IssuerPublicKey>
	</References>

	<Attributes>
		<Attribute issuanceMode="issuer" name="civilStatus" type="enum">
			<EnumValue>Marriage</EnumValue>
			<EnumValue>NeverMarried</EnumValue>
			<EnumValue>Widowed</EnumValue>
			<EnumValue>LegallySeparated</EnumValue>
			<EnumValue>AnnulledMarriage</EnumValue>
			<EnumValue>Divorced</EnumValue>
			<EnumValue>Common-lawPartner</EnumValue>
		</Attribute>
		<Attribute issuanceMode="issuer" name="officialLanguage"
			type="enum">
			<EnumValue>German</EnumValue>
			<EnumValue>French</EnumValue>
			<EnumValue>Italian</EnumValue>
			<EnumValue>Rhaeto-Romanic</EnumValue>
		</Attribute>
		<Attribute issuanceMode="known" name="driverCategory"
			type="enum">
			<EnumValue>A1</EnumValue>
			<EnumValue>B</EnumValue>
			<EnumValue>B1</EnumValue>
			<EnumValue>C</EnumValue>
			<EnumValue>C1</EnumValue>
			<EnumValue>D</EnumValue>
			<EnumValue>D1</EnumValue>
			<EnumValue>BE</EnumValue>
			<EnumValue>CE</EnumValue>
			<EnumValue>DE</EnumValue>
			<EnumValue>C1E</EnumValue>
			<EnumValue>D1E</EnumValue>
			<EnumValue>F</EnumValue>
			<EnumValue>G</EnumValue>
			<EnumValue>M</EnumValue>
		</Attribute>
		<Attribute issuanceMode="hidden" name="sex" type="enum">
			<EnumValue>Male</EnumValue>
			<EnumValue>Female</EnumValue>
		</Attribute>
	</Attributes>

	<Features />

	<Implementation>
		<PrimeEncoding name="peCivilStatus" numValues="7">
			<PrimeFactor attName="civilStatus" attValue="Marriage">3</PrimeFactor>
            <PrimeFactor attName="civilStatus" attValue="NeverMarried">5</PrimeFactor>
			<PrimeFactor attName="civilStatus" attValue="Widowed">7</PrimeFactor>
			<PrimeFactor attName="civilStatus" attValue="LegallySeparated">11</PrimeFactor>
			<PrimeFactor attName="civilStatus" attValue="AnnulledMarriage">13</PrimeFactor>
			<PrimeFactor attName="civilStatus" attValue="Divorced">17</PrimeFactor>
			<PrimeFactor attName="civilStatus" attValue="Common-lawPartner">19</PrimeFactor>
		</PrimeEncoding>
            <PrimeEncoding name="peOfficialLanguage" numValues="4">
            <PrimeFactor attName="officialLanguage" attValue="German">23</PrimeFactor>
            <PrimeFactor attName="officialLanguage" attValue="French">29</PrimeFactor>
            <PrimeFactor attName="officialLanguage" attValue="Italian">31</PrimeFactor>
            <PrimeFactor attName="officialLanguage" attValue="Rhaeto-Romanic">37</PrimeFactor>
        </PrimeEncoding>
		<PrimeEncoding name="peDriverCategory" numValues="15">
			<PrimeFactor attName="driverCategory" attValue="A1">3</PrimeFactor>
			<PrimeFactor attName="driverCategory" attValue="B">5</PrimeFactor>
			<PrimeFactor attName="driverCategory" attValue="B1">7</PrimeFactor>
			<PrimeFactor attName="driverCategory" attValue="C">11</PrimeFactor>
			<PrimeFactor attName="driverCategory" attValue="C1">13</PrimeFactor>
			<PrimeFactor attName="driverCategory" attValue="D">17</PrimeFactor>
			<PrimeFactor attName="driverCategory" attValue="D1">19</PrimeFactor>
			<PrimeFactor attName="driverCategory" attValue="BE">23</PrimeFactor>
			<PrimeFactor attName="driverCategory" attValue="CE">29</PrimeFactor>
			<PrimeFactor attName="driverCategory" attValue="DE">31</PrimeFactor>
			<PrimeFactor attName="driverCategory" attValue="C1E">37</PrimeFactor>
			<PrimeFactor attName="driverCategory" attValue="D1E">41</PrimeFactor>
			<PrimeFactor attName="driverCategory" attValue="F">43</PrimeFactor>
			<PrimeFactor attName="driverCategory" attValue="G">47</PrimeFactor>
			<PrimeFactor attName="driverCategory" attValue="M">53</PrimeFactor>
		</PrimeEncoding>
        <PrimeEncoding name="peSex" numValues="2">
            <PrimeFactor attName="sex" attValue="Male">41</PrimeFactor>
            <PrimeFactor attName="sex" attValue="Female">43</PrimeFactor>
        </PrimeEncoding>
		<AttributeOrder>
			<Attribute name="peCivilStatus">1</Attribute>
			<Attribute name="peOfficialLanguage">2</Attribute>
            <Attribute name="peDriverCategory">3</Attribute>
            <Attribute name="peSex">4</Attribute>
		</AttributeOrder>
	</Implementation>

</CredentialStructure>

=== lamductan/dblacr/files/issuerData/CredStruct5.xml
<?xml version="1.0" encoding="UTF-8"?>
<CredentialStructure xmlns="http://www.zurich.ibm.com/security/idemix/credentialStructure"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xsi:schemaLocation="http://www.zurich.ibm.com/security/idemix/credentialStructure ../xsd/CredentialStructure.xsd">

	<References>
		<IssuerPublicKey>
			http://www.zurich.ibm.com/security/idmx/v2/testIssuer/ipk.xml
		</IssuerPublicKey>
	</References>

	<Attributes>
		<Attribute issuanceMode="known" name="civilStatus" type="enum">
			<EnumValue>Marriage</EnumValue>
			<EnumValue>NeverMarried</EnumValue>
			<EnumValue>Widowed</EnumValue>
			<EnumValue>LegallySeparated</EnumValue>
			<EnumValue>AnnulledMarriage</EnumValue>
			<EnumValue>Divorced</EnumValue>
			<EnumValue>Common-lawPartner</EnumValue>
		</Attribute>
		<Attribute issuanceMode="hidden" name="officialLanguage"
			type="enum">
			<EnumValue>German</EnumValue>
			<EnumValue>French</EnumValue>
			<EnumValue>Italian</EnumValue>
			<EnumValue>Rhaeto-Romanic</EnumValue>
		</Attribute>
	</Attributes>

	<Features />

	<Implementation>
		<PrimeEncoding name="primeEncoding1" numValues="10">
			<PrimeFactor attName="civilStatus" attValue="Marriage">3
			</PrimeFactor>
			<PrimeFactor attName="civilStatus" attValue="NeverMarried">5
			</PrimeFactor>
			<PrimeFactor attName="civilStatus" attValue="Widowed">7
			</PrimeFactor>
			<PrimeFactor attName="civilStatus" attValue="LegallySeparated">11
			</PrimeFactor>
			<PrimeFactor attName="civilStatus" attValue="AnnulledMarriage">13
			</PrimeFactor>
			<PrimeFactor attName="civilStatus" attValue="Divorced">17
			</PrimeFactor>
			<PrimeFactor attName="civilStatus" attValue="Common-lawPartner">19
			</PrimeFactor>
		</PrimeEncoding>
		<PrimeEncoding name="primeEncoding2" numValues="10">
			<PrimeFactor attName="officialLanguage" attValue="German">3
			</PrimeFactor>
			<PrimeFactor attName="officialLanguage" attValue="French">5
			</PrimeFactor>
			<PrimeFactor attName="officialLanguage" attValue="Italian">7
			</PrimeFactor>
			<PrimeFactor attName="officialLanguage" attValue="Rhaeto-Romanic">11
			</PrimeFactor>
		</PrimeEncoding>
		<AttributeOrder>
			<Attribute name="primeEncoding1">1</Attribute>
			<Attribute name="primeEncoding2">2</Attribute>
		</AttributeOrder>
	</Implementation>

</CredentialStructure>

=== lamductan/dblacr/files/issuerData/CredStruct4.xml
<?xml version="1.0" encoding="UTF-8"?>
<CredentialStructure xmlns="http://www.zurich.ibm.com/security/idemix/credentialStructure"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xsi:schemaLocation="http://www.zurich.ibm.com/security/idemix/credentialStructure ../xsd/CredentialStructure.xsd">

	<References>
		<IssuerPublicKey>
			http://www.zurich.ibm.com/security/idmx/v2/testIssuer/ipk.xml
		</IssuerPublicKey>
	</References>
	
	<Attributes>
		<Attribute issuanceMode="known" name="attr1" type="int" />
		<Attribute issuanceMode="committed" name="attr2" type="int" />
		<Attribute issuanceMode="hidden" name="attr3" type="int" />
		<Attribute issuanceMode="hidden" name="attr4" type="int" />
		<Attribute issuanceMode="known" name="attr5" type="int" />
	</Attributes>

	<Features/>

	<Implementation>
		<AttributeOrder>
			<Attribute name="attr1">1</Attribute>
			<Attribute name="attr2">2</Attribute>
			<Attribute name="attr3">3</Attribute>
			<Attribute name="attr4">4</Attribute>
			<Attribute name="attr5">5</Attribute>
		</AttributeOrder>
	</Implementation>

</CredentialStructure>
