=== lamductan/dblacr/files/xsd/IdmxProof.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://www.zurich.ibm.com/security/idemix" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:idemix="http://www.zurich.ibm.com/security/idemix">
  <xs:element name="IdmxProof">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="idemix:Challenge"/>
        <xs:element ref="idemix:SmartcardNonce" minOccurs="0"/>
        <xs:element ref="idemix:CommonValues"/>
        <xs:element ref="idemix:Values"/>
        <xs:element ref="idemix:VerifiableEncryptions"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Challenge" type="xs:integer"/>
  <xs:element name="SmartcardNonce" type="xs:base64Binary"/>
  <xs:element name="CommonValues">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="idemix:CommonValue"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="CommonValue">
    <xs:complexType mixed="true">
      <xs:attribute name="key" use="required" type="xs:anyURI"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Values">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="idemix:Value"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Value">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="idemix:SValueCGAND"/>
        <xs:element ref="idemix:SValueCGNOT"/>
        <xs:element ref="idemix:SValueCGOR"/>
        <xs:element ref="idemix:SValueIP"/>
        <xs:element ref="idemix:SValueProveCL"/>
      </xs:choice>
      <xs:attribute name="key" use="required"/>
      <xs:attribute name="type" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="SValueCGAND">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="idemix:mHat_h"/>
        <xs:element ref="idemix:rHat"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="mHat_h" type="xs:integer"/>
  <xs:element name="rHat" type="xs:integer"/>
  <xs:element name="SValueCGNOT">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="idemix:aHat"/>
        <xs:element ref="idemix:bHat"/>
        <xs:element ref="idemix:rHatPrime"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="aHat" type="xs:integer"/>
  <xs:element name="bHat" type="xs:integer"/>
  <xs:element name="rHatPrime" type="xs:integer"/>
  <xs:element name="SValueCGOR">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="idemix:mHat_i"/>
        <xs:element ref="idemix:alphaHat"/>
        <xs:element ref="idemix:betaHat"/>
        <xs:element ref="idemix:rHat_0"/>
        <xs:element ref="idemix:rHat_1"/>
        <xs:element ref="idemix:rHat_2"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="mHat_i" type="xs:integer"/>
  <xs:element name="alphaHat" type="xs:integer"/>
  <xs:element name="betaHat" type="xs:integer"/>
  <xs:element name="SValueIP">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="idemix:AlphaHat"/>
        <xs:element ref="idemix:uHat_0"/>
        <xs:element ref="idemix:uHat_1"/>
        <xs:element ref="idemix:uHat_2"/>
        <xs:element ref="idemix:uHat_3"/>
        <xs:element ref="idemix:uHat_4"/>
        <xs:element ref="idemix:rHat_0"/>
        <xs:element ref="idemix:rHat_1"/>
        <xs:element ref="idemix:rHat_2"/>
        <xs:element ref="idemix:rHat_3"/>
        <xs:element ref="idemix:rHat_4"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="AlphaHat" type="xs:integer"/>
  <xs:element name="uHat_0" type="xs:integer"/>
  <xs:element name="uHat_1" type="xs:integer"/>
  <xs:element name="uHat_2" type="xs:integer"/>
  <xs:element name="uHat_3" type="xs:integer"/>
  <xs:element name="uHat_4">
    <xs:complexType/>
  </xs:element>
  <xs:element name="rHat_3" type="xs:integer"/>
  <xs:element name="rHat_4" type="xs:integer"/>
  <xs:element name="SValueProveCL">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="idemix:eHat"/>
        <xs:element ref="idemix:vHatPrime"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="eHat" type="xs:string"/>
  <xs:element name="vHatPrime" type="xs:string"/>
  <xs:element name="VerifiableEncryptions">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="idemix:VerifiableEncryption"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="VerifiableEncryption">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="idemix:Locations"/>
        <xs:element ref="idemix:Elements"/>
      </xs:sequence>
      <xs:attribute name="key" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Locations">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="idemix:VEPublicKeyLocation"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="VEPublicKeyLocation" type="xs:anyURI"/>
  <xs:element name="Elements">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="idemix:Label"/>
        <xs:element ref="idemix:u"/>
        <xs:element ref="idemix:e"/>
        <xs:element ref="idemix:v"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Label" type="xs:integer"/>
  <xs:element name="u" type="xs:integer"/>
  <xs:element name="e" type="xs:integer"/>
  <xs:element name="v" type="xs:integer"/>
  <xs:element name="rHat_0" type="xs:integer"/>
  <xs:element name="rHat_1" type="xs:integer"/>
  <xs:element name="rHat_2" type="xs:integer"/>
</xs:schema>

=== lamductan/dblacr/files/send/peNot1_proof.xml
<?xml version="1.0" encoding="UTF-8"?><IdmxProof xmlns="http://www.zurich.ibm.com/security/idemix" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.zurich.ibm.com/security/idemix ../xsd/IdmxProof.xsd">
  <Challenge>43432846806140296189744912369782690256873582036103115540138701548678225748626</Challenge>
  <CommonValues>
    <CommonValue key="gp">78485280485625733211402793534323449321117898710088543846747559831834759431000</CommonValue>
    <CommonValue key="http://www.ngo.org/CredStruct5.xml;someRandomNameMatchingTheOneInTheProofSpec">27835993612678455121356366761627511471961637655894710593877733995690764413724743246582849009122807932926636950314148326979153752389465946493880514136478705291682492647899756968001712418965875298458999176465335325843470965544323894051924348206351195697078676948833667217568186356825509770048179992410252821460</CommonValue>
    <CommonValue key="http://www.ngo.org/CredStruct5.xml;someRandomNameMatchingTheOneInTheProofSpec;issuerPk">36208523169489658024847489255733158291125038638410703786015367110824921513092</CommonValue>
    <CommonValue key="id1;NOT">104807522603692207725070758923248165257047209405340872133773778912969524286193191661947701510423383087039669630184984005171870913102478219424509035656425182132030025930986976172826472946874544238396799695898131273679455424147195074570561767904601366593092452339864827165497490297481141967004965149976439520984</CommonValue>
    <CommonValue key="id2;NOT">19695031008394640896084907521082224545672512853786442475099088715026964386868716611478414730850004816980756282928865548432434125345934457177502118494748829526480655456132586775905206778153756937957414395873723850333355244967129067260407215039619655729953248083940291730252448509721501406014301544181041049593</CommonValue>
    <CommonValue key="proofSpecHash">46675211165942090672716661574690282831231834750944021768352506659382399784662</CommonValue>
    <CommonValue key="sp">19313454934015494502853372660485364277088851954979011267331898025266929871326</CommonValue>
  </CommonValues>
  <Values>
    <Value key="id1;NOT:rHat" type="BigInteger">28312786171133035885478333026783719077253929774481825452522416889177146960837756318946521384812295899443901367582897236599719122362735757500715531560053500569924061893707800714243525868413029173499408486821645469046081993104071409553274649336382499873449459645561393810352184195026035378742926458432419266573862203510110461481235979153876732286104498063016902897173309787298206258600649450439644978488760029</Value>
    <Value key="id2;NOT" type="SValueCGNOT">
      <SValueCGNOT>
        <aHat>-2994885924564533386746808614910353151187568327388406406521671861659807875765262336597089261530694027794267570961690528662081930444867987421796075219938062913046294361440</aHat>
        <bHat>-2016733070748829394301159876166536167508094363295123079785237644797639526718906437904982492774431507487115606896197841505010479918803102200705000339555795348169790122735</bHat>
        <rHatPrime>-2437293761385945549838546066669730121076439307215217208681726316732960812162330278071585114949340799849349501018401325843546791713125754639620115986761497975703335571645736046820684758936498212209347240451551356428647205930810314495293946470730869575239289895077758074668285205309585942559158122470890548449915090532279760707180051841646994300151370921114943606140204610442323924084277</rHatPrime>
      </SValueCGNOT>
    </Value>
    <Value key="http://www.ngo.org/CredStruct5.xml;someRandomNameMatchingTheOneInTheProofSpec" type="SValueProveCL">
      <SValueProveCL>
        <eHat>-66999733255382505924068426406557972816810859148535446178599979924816503418800602196240364839468877811434353579078778807158385418673983692804253135878658678398358935322930498362</eHat>
        <vHatPrime>-3354295769850547351439769081222716338507066259579099958020420604565325694263744395991071757397188663751543842058141884860536351205326283510268166774876587300803583460682810504737552724212997666103213508853731642057544983293977103100220489630907983046771114570623315065191180721409672549314895130670159817306047719922276362625760028133905758503010085552562120932341051980765118694793472231925889031709968998806826484617951057908772537214472332244370129285490211222679702310477216066849725529218140826832480708215926066198861565119231138067858239749945679811266400330316137853450582303511</vHatPrime>
      </SValueProveCL>
    </Value>
    <Value key="id2" type="BigInteger">49323314805703122181603295316369265490751235189760784789689379805882377396399234010088836519563640493634688699793409217017744485733646853449652768810860787946011223712893237312</Value>
    <Value key="id1" type="BigInteger">16144871980700660025381968522153538690960974196012843258168310561991752743180011219387414344183795789980056170053471770416857232051697540621761115244863194368752707533436158831</Value>
    <Value key="id1;NOT" type="SValueCGNOT">
      <SValueCGNOT>
        <aHat>2551846759921176599855391269936590334239359372746943445605109432353704782427722507126962619324079640715342371361247484976055683549097949373604273114262521</aHat>
        <bHat>1024793990856319786476992621007544989099878056367948765909162705988958954209615908210995476158450245176782698336182692585299507733283260812407564367062997</bHat>
        <rHatPrime>217638204385968037565757237141272778603480853317797757738871311294983381348600242160176464754769120835620275761801273400779125202433453173581145413915209796984067058766381864781088534186968850891114290572600374138202817107802982494314262696556532916054245800162346034298590936987811075507846587930428444178709630438430999403878692768533344129560792177619363848551705542780181288246441320</rHatPrime>
      </SValueCGNOT>
    </Value>
    <Value key="id2;NOT:rHat" type="BigInteger">37899946492688999173028857037962330286000038615802557690071747981884386133944271703566343001895809263644320760450625471732621603915275108415125193575241636811336958453056576328158870806484934996543022255030808180157076496976747207729225968056499069615046120818010981493981857856624030965051882209008669269686179903677534727508145346188600623807643785346147335260359906829099446822941518148878364581877379385</Value>
  </Values>
  <TValues>
    <TValue>108251707211408600954583882222742705588764991417559262168810595440522572575944668673423392717968793333175582118430385303433819459213347621149427537265646743501140355107107397791093321709386830432636242036695399027047333346782741533441687918357928828643907164832443047879369590645696952914460856216863876472476</TValue>
    <TValue>112171155738715684357538592313541407696008979264857846339107506877260816578982094946593288799105138822534886868163971492312807231416649766737908940430147363211760275362255664512028475348323635404789566148914468083278751892570352853105716209008182396948568709314663321170652132821398459275179989787037906466845</TValue>
    <TValue>3762933866977063745822522195084508588041613924297506357266688131952316242614817665478699084484138447951203970645829232464069260381932188670225216784326844337147130850023009540748336082019270030829254346000993462120765666351017027646381495384843729827684851976069363563258001798795996122289983001887132093714</TValue>
    <TValue>61434810492638479677282444071773828578063205299827377172228257453961060717984044312654984551607459709042850577519980452871450885202557435369951601620920889194188539797779730541918102024205556812415219339187953899669825569947504379132613493104680181676474512370317732826179712069657264343567129276685308878479</TValue>
    <TValue>59973559990003881565672643617956837871012112228529581816434990113392417985246385103578962661941753924549274514757918036698304241203770531783778249065034868344252750679204803584442379454161362236690597791687207997239024258250191196261493325354511385965658711499033282485358349090518006584924359079400187262569</TValue>
  </TValues>
  <VerifiableEncryptions/>
</IdmxProof>

=== lamductan/dblacr/files/send/cl2s_proof.xml
<?xml version="1.0" encoding="UTF-8"?><IdmxProof xmlns="http://www.zurich.ibm.com/security/idemix" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.zurich.ibm.com/security/idemix ../xsd/IdmxProof.xsd">
  <Challenge>1337</Challenge>
  <SmartcardNonce>AAABA4CBAAA=</SmartcardNonce>
  <CommonValues>
    <CommonValue key="Hello">283671287502675738745401252960954002323362114949843197098753625953143812250936914852448844380531839006468254115829793365275737648337751482364836916865863744170430144017199278520440744015572302261701143281801317756246422722530920577</CommonValue>
    <CommonValue key="gp">78485280485625733211402793534323449321117898710088543846747559831834759431000</CommonValue>
    <CommonValue key="proofSpecHash">41398922248911251744702577397755864786374992717503208545595873930621697205449</CommonValue>
    <CommonValue key="sp">19313454934015494502853372660485364277088851954979011267331898025266929871326</CommonValue>
  </CommonValues>
  <Values>
    <Value key="Hello" type="BigInteger">1935130224482251007174551801011074472257148951587271531436185639953658540272644688991609089576755139428034312409248223037760148374727548350627589446988106976695202620417357438736909990305327059504521029923948781434966199588765183660263997469963797037806890725022818955590433032362005724623310098472638174350804429135163093490579</Value>
    <Value key="smartcard_secret;blibli" type="BigInteger">1788176471760</Value>
  </Values>
  <TValues>
    <TValue>243886358145584953430168609507832142799757610633050005762221448678765613225891301004006530662556458512829116985246681781262701600608270235891383855032942277441339027450510179245187873089726272939881745074668732221685217065504749930</TValue>
  </TValues>
  <VerifiableEncryptions/>
</IdmxProof>

=== lamductan/dblacr/files/send/comm1_proof.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<IdmxProof xmlns="http://www.zurich.ibm.com/security/idemix" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.zurich.ibm.com/security/idemix ../xsd/IdmxProof.xsd">
  <Challenge>82107730514712836260049201115941670629797596404343305771559251535999784593533</Challenge>
  <CommonValues>
    <CommonValue key="gp">78485280485625733211402793534323449321117898710088543846747559831834759431000</CommonValue>
    <CommonValue key="http://www.ngo.org/CredStruct2.xml;someRandomNameMatchingTheOneInTheProofSpec">112832893050429709445392855311005436983103515407661191445851650808522389859333221484126088433869540411095304632340667759667287405042543639211344745379768634279602798225579649411537016610763874248372791996848497622329890079312488523050643347149278684087516920256810354698677625277310581094941178184942431753206</CommonValue>
    <CommonValue key="http://www.ngo.org/CredStruct2.xml;someRandomNameMatchingTheOneInTheProofSpec;issuerPk">36208523169489658024847489255733158291125038638410703786015367110824921513092</CommonValue>
    <CommonValue key="http://www.ngo.org/CredStruct3.xml;someRandomNameMatchingTheOneInTheProofSpec">110191413528255000047635337199272035375912755620620869427805221829611960258132829175673748062033731624612040068296618945970508516010789967058499271181284533381432727334349951845623171111220371604196530192849461025929060798849410494577297752022404476134091481088931757137726346785066034855262827914221028403126</CommonValue>
    <CommonValue key="http://www.ngo.org/CredStruct3.xml;someRandomNameMatchingTheOneInTheProofSpec;issuerPk">36208523169489658024847489255733158291125038638410703786015367110824921513092</CommonValue>
    <CommonValue key="proofSpecHash">85619916305949345377151666090148212812462964163229421362053076839589101873610</CommonValue>
    <CommonValue key="sp">19313454934015494502853372660485364277088851954979011267331898025266929871326</CommonValue>
  </CommonValues>
  <Values>
    <Value key="http://www.ngo.org/CredStruct2.xml;someRandomNameMatchingTheOneInTheProofSpec" type="SValueProveCL">
      <SValueProveCL>
        <eHat>91962832989205574716045064481535122399765220930447826213002923040389349581263863444496412285620901299118454534430775852596158579159441601485804079246848470138608933117097471502</eHat>
        <vHatPrime>-15778497126878829677766482408285413613067190766535343289447189045564887785989595185195721438888395824843496228901873707724153231571668081999207674534154616818872011756517976828837714327479127465088502863994175288698846458513379807520765357761991536441429724886854742832153416899703740459156062373233903714818193905152809698613024352752858248990614236108012165587506212301762259363677030598022019205339578788721429310351356830127215673358902017764447564536183913129257404264077396113526589326531889035255928176640968921631912794479185239227227168747828285650512319159607238799124454955393</vHatPrime>
      </SValueProveCL>
    </Value>
    <Value key="http://www.ngo.org/CredStruct3.xml;someRandomNameMatchingTheOneInTheProofSpec" type="SValueProveCL">
      <SValueProveCL>
        <eHat>-27416351990645219979661399982437457391470164373657433675539161035292907670686736323497332719091860258703378961075420619619223582913026398797327876492681989219311093522512627471</eHat>
        <vHatPrime>-9091217486973575635177516170009880571769111812064202242721649628493971481708041577313383647089949886969488734532723013015904001781768000486415496556644214324377113033542031028850784323704371768812960188627531795185546498356223206925034874220463545469116375096814681243839603034258694514576308657119086479819859708595252643633946806292796314434011694387087520337459868703057095700153669917263510210294068149272602694907418792694150574586406510002262300086293757301084699316861601647638127882836289240031955103434845551027149340361189368644276294243721747351730968842314248339822709078499</vHatPrime>
      </SValueProveCL>
    </Value>
    <Value key="id2" type="BigInteger">1314</Value>
    <Value key="id1" type="BigInteger">29423402028423286945257748157214028185364526361354068645999351956849375064969649650915988295245582016952866536695929979800836542528706150120006707649587820122066092494084497392</Value>
    <Value key="id4" type="BigInteger">1316</Value>
    <Value key="id3" type="BigInteger">19156012344259771623430490973271987300820648591041728420050774763634974092029184588974723279435616517931125914312783742741354336618020511928021944945779615796695104933450067898</Value>
    <Value key="again a random name" type="BigInteger">70933647660275679324429428470197412334942797947557946401989214652013057278020664272095650272185751678802888077184482860332184847822033658619556068908791484587325251855072760627254206721750983582826021706955756020784089234011289476582168050186599601490163594424639285996061142765135116775086047582258064696650432871501747259295798083647173856676747226774255481061100519453445874797555269588258982002546873930</Value>
    <Value key="another random name" type="BigInteger">183776200750726733823435546940895705678296081776673728063430291852829680849972104507624178268351490742315886424398510739292740228379062754284580426165861645818099384993935643697695248205841496652700611354238304616335925543268097468969550048221799333796563881548057264430389047766924956609359745346605396585888528553394776088609772064606588041226348739376705162035407330104091813000534243516119277981379265030</Value>
    <Value key="id6" type="BigInteger">1318</Value>
    <Value key="id5" type="BigInteger">26736132860425499818912539423291550073114972201957847066060347177620901033481963240046493367265296366420943290818323799721706279703864387267059026523631089521185943029981340893</Value>
  </Values>
  <TValues>
    <TValue>83203429407130904576623386642850139862248765398697425574200914711606667480395124243954620932197669145412425939971532383090429789302261558728578780000634843882429235296939379421633253736197680497941658881384793057854427916889286609669885410471481124485322388701834507103489997766189693789899185192550582867850</TValue>
    <TValue>76711587166275269816862017362900659959190423422879112806303871872321839202193950468676512991672577884484953586890215994817503318744144433284237974596455513050347819287373806440378925020700331701495318016311361049669878040275341104413441903688382820850929928196962861056042903305020891376162143056458446372198</TValue>
    <TValue>21377221093861412518323450168727421003147196676302872090822814814682696075142298645414377342919374584659629157521753192325034988146323266140496392627154380618072975659927160503179802801072799703468293604983265515047550299172385423161919356104391905756960211507521421119381658669724161387577383423181902605413</TValue>
    <TValue>3262326576073290850294074292684273367554950031905905426358920452038707639611415172823645142863932525737859306445252624170911949010215646642050655523223413798333814513582970417293449316605069921020744909190481917861209796092623703080027314706292915221105712995068981949175199457870247640740230398608949684352</TValue>
  </TValues>
  <VerifiableEncryptions/>
</IdmxProof>
