=== lamductan/dblacr/files/xsd/IdmxProof.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://www.zurich.ibm.com/security/idemix" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:idemix="http://www.zurich.ibm.com/security/idemix">
  <xs:element name="IdmxProof">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="idemix:Challenge"/>
        <xs:element ref="idemix:SmartcardNonce" minOccurs="0"/>
        <xs:element ref="idemix:CommonValues"/>
        <xs:element ref="idemix:Values"/>
        <xs:element ref="idemix:VerifiableEncryptions"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Challenge" type="xs:integer"/>
  <xs:element name="SmartcardNonce" type="xs:base64Binary"/>
  <xs:element name="CommonValues">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="idemix:CommonValue"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="CommonValue">
    <xs:complexType mixed="true">
      <xs:attribute name="key" use="required" type="xs:anyURI"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Values">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="idemix:Value"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Value">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="idemix:SValueCGAND"/>
        <xs:element ref="idemix:SValueCGNOT"/>
        <xs:element ref="idemix:SValueCGOR"/>
        <xs:element ref="idemix:SValueIP"/>
        <xs:element ref="idemix:SValueProveCL"/>
      </xs:choice>
      <xs:attribute name="key" use="required"/>
      <xs:attribute name="type" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="SValueCGAND">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="idemix:mHat_h"/>
        <xs:element ref="idemix:rHat"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="mHat_h" type="xs:integer"/>
  <xs:element name="rHat" type="xs:integer"/>
  <xs:element name="SValueCGNOT">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="idemix:aHat"/>
        <xs:element ref="idemix:bHat"/>
        <xs:element ref="idemix:rHatPrime"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="aHat" type="xs:integer"/>
  <xs:element name="bHat" type="xs:integer"/>
  <xs:element name="rHatPrime" type="xs:integer"/>
  <xs:element name="SValueCGOR">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="idemix:mHat_i"/>
        <xs:element ref="idemix:alphaHat"/>
        <xs:element ref="idemix:betaHat"/>
        <xs:element ref="idemix:rHat_0"/>
        <xs:element ref="idemix:rHat_1"/>
        <xs:element ref="idemix:rHat_2"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="mHat_i" type="xs:integer"/>
  <xs:element name="alphaHat" type="xs:integer"/>
  <xs:element name="betaHat" type="xs:integer"/>
  <xs:element name="SValueIP">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="idemix:AlphaHat"/>
        <xs:element ref="idemix:uHat_0"/>
        <xs:element ref="idemix:uHat_1"/>
        <xs:element ref="idemix:uHat_2"/>
        <xs:element ref="idemix:uHat_3"/>
        <xs:element ref="idemix:uHat_4"/>
        <xs:element ref="idemix:rHat_0"/>
        <xs:element ref="idemix:rHat_1"/>
        <xs:element ref="idemix:rHat_2"/>
        <xs:element ref="idemix:rHat_3"/>
        <xs:element ref="idemix:rHat_4"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="AlphaHat" type="xs:integer"/>
  <xs:element name="uHat_0" type="xs:integer"/>
  <xs:element name="uHat_1" type="xs:integer"/>
  <xs:element name="uHat_2" type="xs:integer"/>
  <xs:element name="uHat_3" type="xs:integer"/>
  <xs:element name="uHat_4">
    <xs:complexType/>
  </xs:element>
  <xs:element name="rHat_3" type="xs:integer"/>
  <xs:element name="rHat_4" type="xs:integer"/>
  <xs:element name="SValueProveCL">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="idemix:eHat"/>
        <xs:element ref="idemix:vHatPrime"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="eHat" type="xs:string"/>
  <xs:element name="vHatPrime" type="xs:string"/>
  <xs:element name="VerifiableEncryptions">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="idemix:VerifiableEncryption"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="VerifiableEncryption">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="idemix:Locations"/>
        <xs:element ref="idemix:Elements"/>
      </xs:sequence>
      <xs:attribute name="key" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Locations">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="idemix:VEPublicKeyLocation"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="VEPublicKeyLocation" type="xs:anyURI"/>
  <xs:element name="Elements">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="idemix:Label"/>
        <xs:element ref="idemix:u"/>
        <xs:element ref="idemix:e"/>
        <xs:element ref="idemix:v"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Label" type="xs:integer"/>
  <xs:element name="u" type="xs:integer"/>
  <xs:element name="e" type="xs:integer"/>
  <xs:element name="v" type="xs:integer"/>
  <xs:element name="rHat_0" type="xs:integer"/>
  <xs:element name="rHat_1" type="xs:integer"/>
  <xs:element name="rHat_2" type="xs:integer"/>
</xs:schema>

=== lamductan/dblacr/files/send/peAnd1_proof.xml
<?xml version="1.0" encoding="UTF-8"?><IdmxProof xmlns="http://www.zurich.ibm.com/security/idemix" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.zurich.ibm.com/security/idemix ../xsd/IdmxProof.xsd">
  <Challenge>100086052883614236316957067257254003415363624441589581736240462050569079714370</Challenge>
  <CommonValues>
    <CommonValue key="gp">78485280485625733211402793534323449321117898710088543846747559831834759431000</CommonValue>
    <CommonValue key="http://www.ngo.org/CredStruct5.xml;someRandomNameMatchingTheOneInTheProofSpec">20876415721204462178611417209769518444848369687557948765747924517908006097297371038138520154525933025523044385378455176827765465517689786301104788847772513640770065950238198225436892932810793068920183460445651703315776788012626562667077872190688337017126960466944260668043030855252638503334439431770023738606</CommonValue>
    <CommonValue key="http://www.ngo.org/CredStruct5.xml;someRandomNameMatchingTheOneInTheProofSpec;issuerPk">36208523169489658024847489255733158291125038638410703786015367110824921513092</CommonValue>
    <CommonValue key="id2;AND">74630161477421230398187833440738874727594016462004269952782597222669140931120687778342022311314091656602365658438926122711317931341495609162552075421878810160177097922285360082914309110589536547743937595721154829528393944831311495777981986541883364277150235135738434050517331934947496578303921478859208158562</CommonValue>
    <CommonValue key="proofSpecHash">106349760623976657391258455275446593014569806941402073194625287387317747806285</CommonValue>
    <CommonValue key="sp">19313454934015494502853372660485364277088851954979011267331898025266929871326</CommonValue>
  </CommonValues>
  <Values>
    <Value key="http://www.ngo.org/CredStruct5.xml;someRandomNameMatchingTheOneInTheProofSpec" type="SValueProveCL">
      <SValueProveCL>
        <eHat>-113587853526663340656424019393125160727358840778610157907720305818205104629039493882634196575958642043225485388447956758297488351383813214257933668584920799898092293354873473541</eHat>
        <vHatPrime>-13367923060853140189714719332427234207424585129410722273019839152430783997131696059542880761583185134899165792772074447585066509977953915504853406125362274997953616600926067579728040310361416432959310370044306627220697161639058600748154474285337197817293823984993321326167733560154359851676596306989232713658889110405308495257616916855519993512122447884056745674382297478711122092196566223576807487326988386719107650046617319376850954048432854212838571899914338322053516681840722521035866556196735541332978615824660867162187562609827991088560738596083471799258359435133678074974226662257</vHatPrime>
      </SValueProveCL>
    </Value>
    <Value key="id2;AND" type="SValueCGAND">
      <SValueCGAND>
        <mHat_h>26352845274621165023295559773121986241260659284123082461456220973090143376846131465973081509133368313900725367188076043262361110279860495569880530384638461284575</mHat_h>
        <rHat>-171752433079304347176633840572604432098794581164840893690490316743844442301910639168495983635628378986024165736923303051779298669808769696650019114137006969407755256684099014684960777891474786210331831460910001472475389433773526691485813916829296695678939985151789695273018526870662716408286228776678580317270523013232540763118641443225011097727331333059311509402576165525738844900437342506691535335370575187</rHat>
      </SValueCGAND>
    </Value>
    <Value key="id2" type="BigInteger">22376354118410204915579805457062817778316108561620837583903711693281346598190958774349634151091938397742760540821163197319707190671473936545330701041212425381453627682883143550</Value>
    <Value key="id1" type="BigInteger">8646061191778609275107809385831732124529826742820074978394664166563645992413355547395462381859290040236968682142667767990181621132227778745481990765611507122407126718678432678</Value>
  </Values>
  <TValues>
    <TValue>56547371442872540291045424446651213829818195627989552702303182556564957919335476291078855947071796430658433371748406922199218572460174604375825700210793680862518066551695156370346255268260426613462492904540214585715439686615860620466522516679147888922606163726044295411873522297765420525816726638003699538418</TValue>
    <TValue>47125991402712799127262216278368509353184725706128427540607278034049344825935457332311477261838490905678238656161523972368123202019200625615240891304170525130606591755799621021033144209498554565586815389301976223019196214027020792359076461765680415065178463111731953753189368805811694789821773838078043446227</TValue>
    <TValue>31213337340243773671993960970007078705556783098419679882963304644201825245752918921381346316324880054224170532802014227598864511105614946342976530426363340421083217167850547765671133532729313256304765688679214051353477484378431686985019815511209001666335464241382438349981760645452760172283844547545483689278</TValue>
  </TValues>
  <VerifiableEncryptions/>
</IdmxProof>

=== lamductan/dblacr/files/send/cl3_proof.xml
<?xml version="1.0" encoding="UTF-8"?><IdmxProof xmlns="http://www.zurich.ibm.com/security/idemix" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.zurich.ibm.com/security/idemix ../xsd/IdmxProof.xsd">
  <Challenge>90366344338887561603893701450104573747266038072181303459370615200803514110437</Challenge>
  <CommonValues>
    <CommonValue key="gp">78485280485625733211402793534323449321117898710088543846747559831834759431000</CommonValue>
    <CommonValue key="http://www.ngo.org/CredStruct2.xml;someRandomNameMatchingTheOneInTheProofSpec">8889242831197853012444890279065527828627603325193476775358495186421237102614889017367180336150071925794103375860644047399573303505379451234031883367293930093636703787829400656667036214213973437075612305864967633125813971734897488157942078946230922765749669193260854528097465175875893658926907766224782660797</CommonValue>
    <CommonValue key="http://www.ngo.org/CredStruct2.xml;someRandomNameMatchingTheOneInTheProofSpec;issuerPk">36208523169489658024847489255733158291125038638410703786015367110824921513092</CommonValue>
    <CommonValue key="http://www.ngo.org/CredStruct3.xml;someOtherRandomNameToMakeItDistinct">39047769446690448590646416736693234222907158979406450022915241530425282168681559632861371924549507869257741096567148470762931338985619069138837223645424307741681360739706270361863482642679845147719306713555651419258023455300371374994707229468095630239821184174278928505723483616872950971089124456628010896547</CommonValue>
    <CommonValue key="http://www.ngo.org/CredStruct3.xml;someOtherRandomNameToMakeItDistinct;issuerPk">36208523169489658024847489255733158291125038638410703786015367110824921513092</CommonValue>
    <CommonValue key="http://www.ngo.org/CredStruct3.xml;someRandomNameMatchingTheOneInTheProofSpec">25084210398414836689263111805242996696445126558650246929448458461293783392050943570111692220164780687639859399661672595273951215455559365889123135671100512843114965990691953979925250524140303218678159760538144465803078481171960035220013523840927681317005022882154395789060437606735965937675943261599707758134</CommonValue>
    <CommonValue key="http://www.ngo.org/CredStruct3.xml;someRandomNameMatchingTheOneInTheProofSpec;issuerPk">36208523169489658024847489255733158291125038638410703786015367110824921513092</CommonValue>
    <CommonValue key="proofSpecHash">76085275903874416013378714996515243184501471169726125730677078674585901654338</CommonValue>
    <CommonValue key="sp">19313454934015494502853372660485364277088851954979011267331898025266929871326</CommonValue>
  </CommonValues>
  <Values>
    <Value key="id2" type="BigInteger">1314</Value>
    <Value key="http://www.ngo.org/CredStruct3.xml;someRandomNameMatchingTheOneInTheProofSpec" type="SValueProveCL">
      <SValueProveCL>
        <eHat>-40502231149276035694228467035787294354640935957562316313761654447665549373131103700024314166449173262649614863860526991639149200207719711538565462004131852585681182573338008823</eHat>
        <vHatPrime>-18008176806711011264267058691143760960699763216871943806681678232677144269239017511225310407559145696553091441317423402372652896378401376037686375195049431499559726288095204500552974823225624897288563361668858535153101163694678942201350521767512581704361882383038728319608948158083995453257183641005241490134982117834044623119095646647097982382314192410366365336457691881207849831694257387708102238547280601425051729763777898336907517454809517677263031988632449975337285163229703309428186121747202227679518450470013533042050950575405882682099794249326005993977405918086670302517775558182</vHatPrime>
      </SValueProveCL>
    </Value>
    <Value key="id1" type="BigInteger">1313</Value>
    <Value key="id6" type="BigInteger">1318</Value>
    <Value key="id5" type="BigInteger">1317</Value>
    <Value key="id4" type="BigInteger">1316</Value>
    <Value key="id3" type="BigInteger">1315</Value>
    <Value key="http://www.ngo.org/CredStruct3.xml;someOtherRandomNameToMakeItDistinct" type="SValueProveCL">
      <SValueProveCL>
        <eHat>-77119374977447603252375143810673186230052562470601916872804203277580333526205793531173294912803062674490127286990792462313355035422224917300336369498691081741304007369344122685</eHat>
        <vHatPrime>-3634655184882999680831398579707894650833093243009841372528595699934734508550171176271897407056577226300345376329489020101423694382064003689183212853572347073613265972671487652393791236294868928661049892391416800525316525298495788622752074665140317081185519419641521604132757285480431838579093461659520976807461108004186666098486032400175302242087369318451288165005499939092566476670644143488471232610571060487306139689890339251336343629799385996964066509227455162854761477452787970050367989648090707545609140361128247634157730698019637342026635063132156540352464869265955313839329809926</vHatPrime>
      </SValueProveCL>
    </Value>
    <Value key="http://www.ngo.org/CredStruct2.xml;someRandomNameMatchingTheOneInTheProofSpec" type="SValueProveCL">
      <SValueProveCL>
        <eHat>-61337225236069050488698314114812519865508642077856517299082949886026747473999530423910116709759208726451965417184444896008953098056032887651582735106465400157943385881873175297</eHat>
        <vHatPrime>-8257835230900448952428379926522803320018097513102690684641338234738097012496511196360554971211786335069501573561127728609252112742616678546862137213894568280097363833792625152143577928886742630941331916281887344212692131663567405104527002083070958648309270528014939710235147748655211323155770454128298667591807654452224589605212644093760850473127067779455263774722120552237644475573471549244859033015845133566377294022972914337185309138673172596140820532053631906099702667411233253580502384464044153775817387406132310575223607842359034850934546608229838320360821787605636659338012531528</vHatPrime>
      </SValueProveCL>
    </Value>
  </Values>
  <TValues>
    <TValue>80528601841934306575510176760379067140129897367801710774144669885731251727225160241606700708721480555972920351882119297632924989819961794057896554809574244844824696023548033480115904315837270498086897148635125445063517584797425928786019113541381814773981651962325143527426768044006055825667144497232130800923</TValue>
    <TValue>60383052051424641472151297912727588964187233758670504642869970471723283869728597565305925880994299056931398039062716700770820993045515736741171247258061925355227851526488524343054677200414469573219641570492453686584075113661967914929149993101146777358018175234291907122319388734971093550250411824040742998414</TValue>
    <TValue>32176049265261898373081077077107466111042157189375146191241705448306926307774922350258323004873198433056716663697391522919479369300778433468551938405939194566825933156010080331358656655194654121830604711982219590727422429359275660088027343842409653166301057192808550733890942146632496584985764895947131382678</TValue>
  </TValues>
  <VerifiableEncryptions/>
</IdmxProof>

=== lamductan/dblacr/files/send/clNoValues_proof.xml
<?xml version="1.0" encoding="UTF-8"?><IdmxProof xmlns="http://www.zurich.ibm.com/security/idemix" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.zurich.ibm.com/security/idemix ../xsd/IdmxProof.xsd">
  <Challenge>115736883427394239017951909374277519946238351091318445707431963554196787234436</Challenge>
  <CommonValues>
    <CommonValue key="gp">78485280485625733211402793534323449321117898710088543846747559831834759431000</CommonValue>
    <CommonValue key="http://www.ngo.org/CredStruct0.xml;someRandomName">110872554347409395466821547418158596859588926919416071434755376314975447108666115766346751248807612762429942209134028362932455260511533347106497511419012926722437432363843288113834228483278131246630914026687258775368151892532092483251076466464592896935441965221091487822723549569301172561748016792875152132712</CommonValue>
    <CommonValue key="http://www.ngo.org/CredStruct0.xml;someRandomName;issuerPk">36208523169489658024847489255733158291125038638410703786015367110824921513092</CommonValue>
    <CommonValue key="proofSpecHash">106273054827501621825553214256000356512999714724107011085366830276057952479094</CommonValue>
    <CommonValue key="sp">19313454934015494502853372660485364277088851954979011267331898025266929871326</CommonValue>
  </CommonValues>
  <Values>
    <Value key="http://www.ngo.org/CredStruct0.xml;someRandomName" type="SValueProveCL">
      <SValueProveCL>
        <eHat>-63206176126006754523135018337400689058444612730139812519926320989505168959633005633931550695301183661687903201368972087129456430291598052999269542827563409044852466263139449785</eHat>
        <vHatPrime>-8336556732968160614509933252385255477838740249767843226862776943036043432674316581878339524469135137221249341646562335791358823648332266683120964717630100572149908298523852682053422009144045141961952685895283618713563035442334526903792231234587427190009009156694866490986626043373175955361486799931586054367262276445385299269287248989214456621784445586821910423940645437561782056506406494821441549366686428590614013181042699153917976929327300520086632447528019483177344319466174493836226691734249400446589293069259185626536724580066225277302099936102232902511844540806335953783178358097</vHatPrime>
      </SValueProveCL>
    </Value>
  </Values>
  <TValues>
    <TValue>106972397973019779934736719960042536527923540267218740122689467318580657185284384811489347787290390319969650107980792353461428390321665832238444039945474403193656046855999278790355943477523484011649055597124743413354159570874359286986294108993231322144917462491670136422546213312919952256615444470418465178358</TValue>
  </TValues>
  <VerifiableEncryptions/>
</IdmxProof>

=== lamductan/dblacr/files/send/cl2si_proof.xml
<?xml version="1.0" encoding="UTF-8"?><IdmxProof xmlns="http://www.zurich.ibm.com/security/idemix" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.zurich.ibm.com/security/idemix ../xsd/IdmxProof.xsd">
  <Challenge>1337</Challenge>
  <SmartcardNonce>AAABA4CBAAA=</SmartcardNonce>
  <CommonValues>
    <CommonValue key="gp">78485280485625733211402793534323449321117898710088543846747559831834759431000</CommonValue>
    <CommonValue key="proofSpecHash">110235385455268413038339044356950770279552013381599310803714061398052471783956</CommonValue>
    <CommonValue key="sp">19313454934015494502853372660485364277088851954979011267331898025266929871326</CommonValue>
    <CommonValue key="toBeIssued">24710151076209636170329704183424777377782608751230222351490834940935742686068196176959331202554795798370265588254378593893077024593543181806382809733145023056567607316489219558295449890150491623584971202819395179555857645933213335727435155500288245278591923158359268186549263493150730497093684401870731083778</CommonValue>
    <CommonValue key="toBeIssued;issuerPk">36208523169489658024847489255733158291125038638410703786015367110824921513092</CommonValue>
  </CommonValues>
  <Values>
    <Value key="smartcard_secret;nameOfSecret" type="BigInteger">1788176471760</Value>
    <Value key="id2" type="BigInteger">2000</Value>
    <Value key="id1" type="BigInteger">1000</Value>
    <Value key="id6" type="BigInteger">56491895304619289587312186104712572435684968796075710106727686313227820620699689360036430151867644153426681081813588438973551598190297048351199761292257113335385907843719221894</Value>
    <Value key="id5" type="BigInteger">12935343322792943415181660527480777066044519757845240939579574401511679535004900748121798965350367364806634108925964934711106246342105635319458755329887125907527386698538992168</Value>
    <Value key="id4" type="BigInteger">20745969024660992141199299377999592937509877369926111940566869898553610355295432425717115182994226688612118860791827923144181925980679243907775653288899401607168093393425328504</Value>
    <Value key="id3" type="BigInteger">6000</Value>
    <Value key="toBeIssued" type="BigInteger">895314282616979059877009196565398405279070424226298001055327668278409356906618840878726129097783138314110277743452012464350345447306155806852828131376895744117438305034467774292763037377783056980722547538837719919755804838263266522588611127115091840812742525828755749681880169778234126931355718029130575557434919108313967877478576004908957471129092002581488296456727297143335142891430998163216588080132563691553980891151579393689541</Value>
  </Values>
  <TValues>
    <TValue>85365527820054022147704396748702074484280588045678623554442271821705952331457042628909688343408962302920572922600851190254260595021053045342735013867942257963299774189182472671195463923696618068303205251082340735953110570328945707734682640560223668806611955496571119540188422172446726409564986399948269994722</TValue>
  </TValues>
  <VerifiableEncryptions/>
</IdmxProof>
