=== lamductan/dblacr/files/xsd/IdmxProof.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://www.zurich.ibm.com/security/idemix" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:idemix="http://www.zurich.ibm.com/security/idemix">
  <xs:element name="IdmxProof">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="idemix:Challenge"/>
        <xs:element ref="idemix:SmartcardNonce" minOccurs="0"/>
        <xs:element ref="idemix:CommonValues"/>
        <xs:element ref="idemix:Values"/>
        <xs:element ref="idemix:VerifiableEncryptions"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Challenge" type="xs:integer"/>
  <xs:element name="SmartcardNonce" type="xs:base64Binary"/>
  <xs:element name="CommonValues">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="idemix:CommonValue"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="CommonValue">
    <xs:complexType mixed="true">
      <xs:attribute name="key" use="required" type="xs:anyURI"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Values">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="idemix:Value"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Value">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="idemix:SValueCGAND"/>
        <xs:element ref="idemix:SValueCGNOT"/>
        <xs:element ref="idemix:SValueCGOR"/>
        <xs:element ref="idemix:SValueIP"/>
        <xs:element ref="idemix:SValueProveCL"/>
      </xs:choice>
      <xs:attribute name="key" use="required"/>
      <xs:attribute name="type" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="SValueCGAND">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="idemix:mHat_h"/>
        <xs:element ref="idemix:rHat"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="mHat_h" type="xs:integer"/>
  <xs:element name="rHat" type="xs:integer"/>
  <xs:element name="SValueCGNOT">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="idemix:aHat"/>
        <xs:element ref="idemix:bHat"/>
        <xs:element ref="idemix:rHatPrime"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="aHat" type="xs:integer"/>
  <xs:element name="bHat" type="xs:integer"/>
  <xs:element name="rHatPrime" type="xs:integer"/>
  <xs:element name="SValueCGOR">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="idemix:mHat_i"/>
        <xs:element ref="idemix:alphaHat"/>
        <xs:element ref="idemix:betaHat"/>
        <xs:element ref="idemix:rHat_0"/>
        <xs:element ref="idemix:rHat_1"/>
        <xs:element ref="idemix:rHat_2"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="mHat_i" type="xs:integer"/>
  <xs:element name="alphaHat" type="xs:integer"/>
  <xs:element name="betaHat" type="xs:integer"/>
  <xs:element name="SValueIP">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="idemix:AlphaHat"/>
        <xs:element ref="idemix:uHat_0"/>
        <xs:element ref="idemix:uHat_1"/>
        <xs:element ref="idemix:uHat_2"/>
        <xs:element ref="idemix:uHat_3"/>
        <xs:element ref="idemix:uHat_4"/>
        <xs:element ref="idemix:rHat_0"/>
        <xs:element ref="idemix:rHat_1"/>
        <xs:element ref="idemix:rHat_2"/>
        <xs:element ref="idemix:rHat_3"/>
        <xs:element ref="idemix:rHat_4"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="AlphaHat" type="xs:integer"/>
  <xs:element name="uHat_0" type="xs:integer"/>
  <xs:element name="uHat_1" type="xs:integer"/>
  <xs:element name="uHat_2" type="xs:integer"/>
  <xs:element name="uHat_3" type="xs:integer"/>
  <xs:element name="uHat_4">
    <xs:complexType/>
  </xs:element>
  <xs:element name="rHat_3" type="xs:integer"/>
  <xs:element name="rHat_4" type="xs:integer"/>
  <xs:element name="SValueProveCL">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="idemix:eHat"/>
        <xs:element ref="idemix:vHatPrime"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="eHat" type="xs:string"/>
  <xs:element name="vHatPrime" type="xs:string"/>
  <xs:element name="VerifiableEncryptions">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="idemix:VerifiableEncryption"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="VerifiableEncryption">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="idemix:Locations"/>
        <xs:element ref="idemix:Elements"/>
      </xs:sequence>
      <xs:attribute name="key" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Locations">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="idemix:VEPublicKeyLocation"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="VEPublicKeyLocation" type="xs:anyURI"/>
  <xs:element name="Elements">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="idemix:Label"/>
        <xs:element ref="idemix:u"/>
        <xs:element ref="idemix:e"/>
        <xs:element ref="idemix:v"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Label" type="xs:integer"/>
  <xs:element name="u" type="xs:integer"/>
  <xs:element name="e" type="xs:integer"/>
  <xs:element name="v" type="xs:integer"/>
  <xs:element name="rHat_0" type="xs:integer"/>
  <xs:element name="rHat_1" type="xs:integer"/>
  <xs:element name="rHat_2" type="xs:integer"/>
</xs:schema>

=== lamductan/dblacr/files/send/peOr1_proof.xml
<?xml version="1.0" encoding="UTF-8"?><IdmxProof xmlns="http://www.zurich.ibm.com/security/idemix" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.zurich.ibm.com/security/idemix ../xsd/IdmxProof.xsd">
  <Challenge>10162243957821395019463189772687525101863793830277214691493884361911782074186</Challenge>
  <CommonValues>
    <CommonValue key="gp">78485280485625733211402793534323449321117898710088543846747559831834759431000</CommonValue>
    <CommonValue key="http://www.ngo.org/CredStruct5.xml;someRandomNameMatchingTheOneInTheProofSpec">38603316938116026915739356124126146769876157383853315051588829004811470887537051003348333647331385662519234295453941535410298065000778703360162886326315336390547181158756496848906810512246723326893500626625119106728210717484381828734214754725552929195430630589514847971689429949362703919691050248687465426414</CommonValue>
    <CommonValue key="http://www.ngo.org/CredStruct5.xml;someRandomNameMatchingTheOneInTheProofSpec;issuerPk">36208523169489658024847489255733158291125038638410703786015367110824921513092</CommonValue>
    <CommonValue key="id1;OR">64687675755853680066396060323274716442220112391520479800492025703336222529735575968913528658372289562458532310506280414221009689076848340466147384188123851907390830080031629839200359505912486265783658118811017107481432702277074351538695601597454969843526612903260606671133456482385714332931089665532751168766</CommonValue>
    <CommonValue key="id2;OR">8015733551786784292117303422124212498301405552347883651310657546269579922860925430615737207603404611407863059561843581648204750999222647491886075014265003286917574388492478521373772603232245202360817758395214546901107368149636112796081993092244482988230943069524707363178559693421402209442967980828561491175</CommonValue>
    <CommonValue key="proofSpecHash">46675211165942090672716661574690282831231834750944021768352506659382399784662</CommonValue>
    <CommonValue key="sp">19313454934015494502853372660485364277088851954979011267331898025266929871326</CommonValue>
  </CommonValues>
  <Values>
    <Value key="http://www.ngo.org/CredStruct5.xml;someRandomNameMatchingTheOneInTheProofSpec" type="SValueProveCL">
      <SValueProveCL>
        <eHat>-112583597462186911097823696472674285093938005422918798758633345967198815930692287577733214741592450023039363307525839869853163523862585615815620245971828510329265852366162921656</eHat>
        <vHatPrime>-1001635579684932950603536909538313760642454676314705910640143175793039100329077164578571040012959495191685034252963323518870876052422696762432139160444399934925720966640211715243605348187771100759535357286357509977004902226538282968609800133257824880633787045735648181056494687042505500996775822677054396454379391544769605476384592982605791576901291090578010484084159764745669977841536688800139632445085073275448051456613569285284127927040167571858104153395449866036428775941403437810111243363438853588397642096154015785703692083749833281463231436466934789459452418697398414224471963724</vHatPrime>
      </SValueProveCL>
    </Value>
    <Value key="id2" type="BigInteger">52938627116273818526275932994015125979103421424663722257462543520682402857185770117279185497090523598517802469245175868022518488771789331134293126916616680820464885820008018162</Value>
    <Value key="id1" type="BigInteger">20478736924235113247422029201326389176508569778840148408026370052530259002721456324389629491309627898536594655793010423293846211922290681763938860219344197541902308271189662790</Value>
    <Value key="id2;OR" type="SValueCGOR">
      <SValueCGOR>
        <mHat_i>-94667773419425825717681182680653562972049320745848055019285363123187143969489494064228095198557249977533864793361270864004631638145075617189488379198442062820232428702063349060</mHat_i>
        <alphaHat>43967332499393991224069833536028209193452080759321133597700583477737001510811121153708870699547151767753931515128646102016279650370276121386069943839549247224398317893300979880</alphaHat>
        <betaHat>-54524256720803117934084513863858988063261066011697346507369136266913541087903595583327853235113981108743341407335246412501884047774944206989967324074962373250841676848569795138</betaHat>
        <rHat_0>47732537816837504360303102408665891451237071777505745324164831571969375902725937557066243184780495173942481233940630170392995656562979384994906832932399047191185048289131868328873579512677468889183253483761684056671599768682618318908181417946976147322349249199683508524283206896659132366727527543936867422956076698731521080111176909634756246737013041870456265663673155500585055203929395096087803808241412208</rHat_0>
        <rHat_1>174784930892463059633319101713612896461240170666365445296808244913571911698791906735860311772937765418159543900824192736081174778537198042005188974747984541698735389476119607530812596979660882659191681289902284122186561075002688691756460659568176978967506942220514619364776257179398943930139854103957362664284319755689117790382790082040433734016535304573606879535520653693284644855937397282281807509462385173</rHat_1>
        <rHat_2>-163743579860253454641028394563829027795356243654030418439698252676688520568311884197005140903457818046010602273119009114308938221480789207312138982116963817252378690521530323171131298386242738937855791378362320783786795217010229692602400742725977708249742076153549443420857697028559144198170489683589735171144410496220910301098245282936812532352455763672171756120814542356529322546402349273785211387875211192</rHat_2>
      </SValueCGOR>
    </Value>
    <Value key="id1;OR" type="SValueCGOR">
      <SValueCGOR>
        <mHat_i>41970744676198453754851586749502419345439848458862143930293624267938336252963070584217453343498810669273349892466368863839093267762636728519371691733188545053281449963263652797</mHat_i>
        <alphaHat>-21434274717388068534342621579361605618203777250985294390652528742785428980664866066401224032590967163257002929529562366241956307016323278384878129679683024624159614798805312788</alphaHat>
        <betaHat>86889913760427875470903186038179077551253910822741054447180190743188809003377476316899967277774752639228941930204411001079479429726734528305016807971368880833189140038442680094</betaHat>
        <rHat_0>-114027832556763152125719030949202766157104667260993308821842488779767251286404378914819577220154413635130553237920332887977557431655658573695744089311992032703936967375768794668664557129104924481511509994897914095704859808421811793055853507083776247839759881075217599721192151875830241238375527883228788550228179326982336316587513624121846063960892209831153011941373124571539215817331480013811597579334547592</rHat_0>
        <rHat_1>2435849471438008008894650424127637642711220116854000868982641802417825294573599491511481918781308631010358820593004255703447688719662081724464816168469553030096598954049426933391264104996084332676872909572519205544388536261504119505974581796156977907364083749770198790344747647825532132671989868161097161270217907835295795250988740354470809413156231918020129333567568438145364238542778870141163038803914558</rHat_1>
        <rHat_2>19323635824044449436699455633617938887000399876234297712349475932329267043289369036197315897973264656116142367962331298815584257908475149913067092486642709223487603561688592345677560298547894809441890069249506056434824698795088352029591055294269790669240519669707363546729802054320590804452319406561447105263180365541513847339628183337213089179003313727462303327857492603465626274798152187078983383071829202</rHat_2>
      </SValueCGOR>
    </Value>
  </Values>
  <TValues>
    <TValue>20329136138192847682637780414074382667657738839561539854296394047613348816546372485455218211855143801103852540740623847839845714180918431136862869710193658306264761343198137108590425252255930225096746878090702596296832011092497426868446674895325030029515996012231367724611170755698475723298892329701821504498</TValue>
    <TValue>52442890708498846795622170935911915257325323099790071993180904355833501504411486930797561742879473946785329179689243881756688118158529508001721273303020779050434256121019760630153223034763858677820859739452543612303311296257073646450164818828531472087840354719019282159225460761696002641071219099665603825520</TValue>
    <TValue>15027316069999199636443787920613559851839745346423330197568494287359629316607044455179425154558726011930915028629504580476876699159411757300429941038978143722968094697862026529453556959932840409937761093008378829652546911008151290175225319455022289603817312813375350885062183649019146633894123290636273998115</TValue>
    <TValue>118386014416831372067462350140549425257320425311421226563114132287734483635512068125615422757149943006649171192120679283361755027033514388699152571580543370955499686526847849367861711193513833591494826055765349760383296491398167133671337654574618729539919060525973041609377107417735320739459489933763855893492</TValue>
    <TValue>27806225100944541027961972375487096771645986439405899928703495096436210356998424998763303454576786521537841014893995913729333951029415241136347138496538728571392757319566994196370005866255143566447172590116559688836588844998025855390114196272368420985751579844106473734712810557854904425821135032067813251820</TValue>
    <TValue>93274869372666685218463677024190368601940359358301528408430305586854379256354891923176421984697434760255261086551636569026024469728841912147840056904009107184828968680273360392056121401890088534360256316321564615362174977793283599157591101325498655426842012883378663121052415853389416658976364729766119796612</TValue>
    <TValue>80241948091999021645408618862258340893389422541642354587904331742923288088637194731232769099279705686194855683677002823561939841913777670940982225472742317138378595183677595831637583084935303711280536085993466660065850432272094990537641722025537594618816031785856585934727562271205467298052586834801920094042</TValue>
  </TValues>
  <VerifiableEncryptions/>
</IdmxProof>
