=== lamductan/dblacr/files/xsd/IssuerUpdateInformation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://www.zurich.ibm.com/security/idemix" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:idemix="http://www.zurich.ibm.com/security/idemix">
  <xs:element name="IssuerUpdateInformation">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="idemix:Location"/>
        <xs:element ref="idemix:Values"/>
        <xs:element ref="idemix:Q"/>
        <xs:element ref="idemix:vPrimePrime"/>
        <xs:element ref="idemix:Nonce"/>
        <xs:element ref="idemix:Context"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Location">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="idemix:IssuerPublicKey"/>
        <xs:element ref="idemix:CredentialStructure"/>
        <xs:element ref="idemix:Update"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="IssuerPublicKey" type="xs:anyURI"/>
  <xs:element name="CredentialStructure" type="xs:anyURI"/>
  <xs:element name="Update" type="xs:anyURI"/>
  <xs:element name="Values">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="idemix:Value"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Value">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="name" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="Q" type="xs:integer"/>
  <xs:element name="vPrimePrime" type="xs:string"/>
  <xs:element name="Nonce" type="xs:integer"/>
  <xs:element name="Context" type="xs:string"/>
</xs:schema>

=== lamductan/dblacr/files/private/issuerRecord1c.xml
<?xml version="1.0" encoding="UTF-8"?><IssuerUpdateInformation xmlns="http://www.zurich.ibm.com/security/idemix" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.zurich.ibm.com/security/idemix ../xsd/IssuerUpdateInformation.xsd">
  <Location>
    <IssuerPublicKey>http://www.issuer.com/ipk.xml</IssuerPublicKey>
    <CredentialStructure>http://www.ngo.org/CredStruct1c.xml</CredentialStructure>
    <Update>http://www.base.of.uri/where/the/updates/will/be/Update_gji0mel50hajioefprj4.xml</Update>
  </Location>
  <Values>
    <Value name="attr4">102787220464222280996129743007714452389327536866272886834038024772423502010111</Value>
    <Value name="attr3">3650481942402582375958668357344705576112980177137059879763127269205158951849</Value>
  </Values>
  <Q>77340615586877000301605944252759882619200858383075263902876433362354492461288726069290380892731387284026920418828737519772664409269044055786141656809217586759711966140908928976633045146803755554815205737979339521836919544248281416149611245835669192247925958259961720290097511242992402091379870295917777738758</Q>
  <vPrimePrime>1886712313377576902346742514526196255042662312355169165251575149544895673976790723668240852236092149474250307356517605719189157119239287954840638728486234075734061720039235959124433454572765281941024178385564390868300841092367043890945209756785232283556359676415160005552358029231439914681009571746269819251508424421759021745704115780932593233202154932292394190442326451304812227409891002905779720574323004672371566909587770338305</vPrimePrime>
  <Nonce>481722685390562291726</Nonce>
  <Context>57132007859431325469155257180381990227612921134850039113478974728701260469495</Context>
</IssuerUpdateInformation>
