=== lamductan/dblacr/files/xsd/IssuerPrivateKey.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema 
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.zurich.ibm.com/security/idemix"
	xmlns="http://www.zurich.ibm.com/security/idemix"
	elementFormDefault="qualified">
  
  <xs:element name="IssuerPrivateKey">
  	<xs:complexType>
  		<xs:all>
  			<xs:element name="References" type="ReferencesType" />
  			<xs:element name="Elements" type="ElementsType" />
  		</xs:all>
  	</xs:complexType>
  </xs:element>
  
  <xs:complexType name="ReferencesType">
  	<xs:all>
  		<xs:element name="IssuerPublicKey" type="xs:anyURI" />
  	</xs:all>
  </xs:complexType>
  
  <xs:complexType name="ElementsType">
  	<xs:all>
  		<xs:element name="n" type="BigIntegerType" />
  		<xs:element name="p" type="BigIntegerType" />
  		<xs:element name="pPrime" type="BigIntegerType" />
  		<xs:element name="q" type="BigIntegerType" />
  		<xs:element name="qPrime" type="BigIntegerType" />
  	</xs:all>
  </xs:complexType>

  <xs:simpleType name="BigIntegerType">
  	<xs:restriction base="xs:string">
  		<xs:whiteSpace value="collapse" />
  		<xs:pattern value="-?[0-9]+" />
    </xs:restriction>
  </xs:simpleType>
  
</xs:schema>

=== lamductan/dblacr/files/private/isk.xml
<?xml version="1.0" encoding="UTF-8"?><IssuerPrivateKey xmlns="http://www.zurich.ibm.com/security/idemix" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.zurich.ibm.com/security/idemix ../xsd/IssuerPrivateKey.xsd">
  <References>
    <IssuerPublicKey>http://www.issuer.com/ipk.xml</IssuerPublicKey>
  </References>
  <Elements>
    <n>119044022186753690018430516777857594963368506134570973357311270757022475907431866561996530390008551579472891604827125833721397252053305134571142913793132219807152566643909997919585593336578843205692900329154693554897764568744373060642870170977183333982530812867790710426944978612698155788787287562342569509073</n>
    <p>11264342164831095804987593495385222138658228124928882687989742495675737265234700835704448532403449517750811184714756548177360769361953087429179906482286459</p>
    <pPrime>5632171082415547902493796747692611069329114062464441343994871247837868632617350417852224266201724758875405592357378274088680384680976543714589953241143229</pPrime>
    <q>10568217872360654302876223086247274870241527544362973681498849586390020014831930819746722153787783000239599980528742681699483959542168818616957571888224547</q>
    <qPrime>5284108936180327151438111543123637435120763772181486840749424793195010007415965409873361076893891500119799990264371340849741979771084409308478785944112273</qPrime>
  </Elements>
</IssuerPrivateKey>
