=== lamductan/dblacr/files/xsd/IssuerPublicKey.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema 
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.zurich.ibm.com/security/idemix"
	xmlns="http://www.zurich.ibm.com/security/idemix"
	elementFormDefault="qualified">
  
  <xs:element name="IssuerPublicKey">
  	<xs:complexType>
  		<xs:all>
  			<xs:element name="References" type="ReferencesType" />
  			<xs:element name="Elements" type="ElementsType" />
  			<xs:element name="Features" type="FeaturesType" />
  		</xs:all>
  	</xs:complexType>
  </xs:element>
  
  <xs:complexType name="ReferencesType">
  	<xs:all>
  		<xs:element name="GroupParameters" type="xs:anyURI" />
  	</xs:all>
  </xs:complexType>
  
  <xs:complexType name="ElementsType">
  	<xs:all>
  		<xs:element name="S" type="BigIntegerType" />
  		<xs:element name="Z" type="BigIntegerType" />
  		<xs:element name="n" type="BigIntegerType" />
  		<xs:element name="Bases" type="BasesType" />
  	</xs:all>
  </xs:complexType>

  <xs:simpleType name="BigIntegerType">
  	<xs:restriction base="xs:string">
  		<xs:whiteSpace value="collapse" />
  		<xs:pattern value="-?[0-9]+" />
    </xs:restriction>
  </xs:simpleType>
  
  <xs:complexType name="BasesType">
  	<xs:sequence>
  		<xs:element name="Base" type="BigIntegerType" maxOccurs="unbounded" />
  	</xs:sequence>
  	<xs:attribute name="num" type="xs:nonNegativeInteger" use="required" />
  </xs:complexType>
  
  <xs:complexType name="FeaturesType">
  	<xs:sequence>
  		<xs:element name="Epoch" type="EpochType" />
  	</xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="EpochType">
  	<xs:attribute name="length" type="xs:nonNegativeInteger" use="required" />
  </xs:complexType>
</xs:schema>

=== lamductan/dblacr/files/issuerData/ipk.xml
<?xml version="1.0" encoding="UTF-8"?><IssuerPublicKey xmlns="http://www.zurich.ibm.com/security/idemix" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.zurich.ibm.com/security/idemix ../xsd/IssuerPublicKey.xsd">
  <References>
    <GroupParameters>http://www.zurich.ibm.com/security/idmx/v2/gp.xml</GroupParameters>
  </References>
  <Elements>
    <S>67254978546586387746371812310799963199648525605698331029534251596232370027172664240407979301953626203319151762261652600759005672320154674443879786091477200196732310064009956256955600787213240490631750504640542741919004918195148381937131971214494976707809949834888578482370086318215794644835662415992756882603</S>
    <Z>66224551169464002663940073750644127130889816679489538701687141754076658510548823635302303655563690504435156823639264274506650345327534057155780665683182685312336929086395707042635093432149841190888314129954385661141288950812080398397620395354073412245066860649679985409261396977542279412842522527918888155531</Z>
    <n>119044022186753690018430516777857594963368506134570973357311270757022475907431866561996530390008551579472891604827125833721397252053305134571142913793132219807152566643909997919585593336578843205692900329154693554897764568744373060642870170977183333982530812867790710426944978612698155788787287562342569509073</n>
    <Bases num="10">
      <Base>32921814524377017041931913576584439560632569931404502353475383371878236583978512140794089573553532245705459408417869416443659319693175867098884370978448886092451288399260225788087061330501562228689833809787781336214456117869525090072024003349054898349464658701210662766987336518999452802422749574128824579840</Base>
      <Base>87476314549821493777780058505429862923998092617241984383215391472141141122383840141310924546514107724464971905212091997802561189889587527200865479986333719356671793348394247583948929910063559632398293480463942305963539783648420426150973020666204973841629140991277405593515579469356096998954830674998016613188</Base>
      <Base>94298075884572525779343592235401695915726512465959188958798755254674037304850522353608138727452862354674608168215325899162059695803481022809246744831177345428743726398367473203508236789513840939284246903684116242708034311840194311381115859325840540655681072912968098478411042141576742425256973097275930737323</Base>
      <Base>839931957231496888652703380557270377728662615278665992520937472916115094568497637515598265489056750318283874734296956721553455332520995542456044853633189619575983145434139970948507251802574833890857188697559092933622770489933135664053534438209437090299592284539481052837367032305682413018719540561902802479</Base>
      <Base>41739693176609816834282144887485658137181272323117851059727411352436331724964662777941733424238577944810495239780830538678519854267434226333440720692540960611619261392134937858992823546292773427339242618479916546973241895709708259981897290685659985409460496658404964746259022783822458904838428368826482810505</Base>
      <Base>60962695669930253132603988374218594382128026965397098653129565912642357029599209955483310232702860446825832748759673449804354839081377942939998055170271928457524131192840576732095772121299315335719551767380154225585786169309572224886555610839204066995347416282514533062313665429663100563367672127474286298873</Base>
      <Base>30599399477063544052747018855331276263518748322654273190564257355413250848935157735859136911290499195823277968821453854213377381969764086367614220786358158923266788960950246675563903536129566318849688849334849380079433847913556816409224821414270057151204208577480491442969099186496475191734893578211950765494</Base>
      <Base>51532983304617639900152284193882172523272555084402222696786586265523751412564044592124823117365978327935262155299365566569767229324516884808377261385214899602869703378606423210879954431725402738349992487709572504675331498848867788602733403838659010088662094401973109354097421953925615769333625323572260544639</Base>
      <Base>89820528823514669012395033010740345220323908334718387522362242196687634130185537411183962763997118565042882226793848491325160237763001478424177889828762634215944424471440449141099570593087681441757718010177025480965425765336988312058700460504895488202247892095999971123248027519120299412732712361892170869820</Base>
      <Base>102641062773139014350009198960543686903776052610755546516489220426795234134867795864445901974512291208648678363556972562875932951817829135749534761442994172541397553992582045674853700988295138202497818595389447935699048713155842724830168970620928324308152965757843366870117398105019136685240809477416355555313</Base>
    </Bases>
  </Elements>
  <Features>
    <Epoch length="432000"/>
  </Features>
</IssuerPublicKey>
