=== lamductan/dblacr/files/xsd/Message.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://www.zurich.ibm.com/security/idemix" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:idemix="http://www.zurich.ibm.com/security/idemix">
  <xs:element name="Message">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="idemix:Values"/>
        <xs:element ref="idemix:TValues"/>
        <xs:element ref="idemix:IssuerAttributes" minOccurs="0"/>
        <xs:element ref="idemix:IdmxProof" minOccurs="0"/>
        <xs:element ref="idemix:Counter"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="IdmxProof">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="idemix:Challenge"/>
        <xs:element ref="idemix:SmartcardNonce" minOccurs="0"/>
        <xs:element ref="idemix:CommonValues" minOccurs="0"/>
        <xs:element ref="idemix:Values"/>
        <xs:element ref="idemix:VerifiableEncryptions"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Challenge" type="xs:integer"/>
  <xs:element name="SmartcardNonce" type="xs:base64Binary"/>
  <xs:element name="CommonValues">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="idemix:CommonValue"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="VerifiableEncryptions">
    <xs:complexType/>
  </xs:element>
  <xs:element name="Counter" type="xs:integer"/>
  <xs:element name="IssuerAttributes">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="idemix:Attribute"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Values">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="idemix:Value"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
    <xs:element name="TValues">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="TValue" type="xs:integer"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Value">
    <xs:complexType mixed="true">
      <xs:attribute name="key" type="xs:string"/>
      <xs:attribute name="name" type="xs:NCName"/>
      <xs:attribute name="type" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="CommonValue">
    <xs:complexType mixed="true">
      <xs:attribute name="key" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Attribute">
    <xs:complexType mixed="true">
      <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== lamductan/dblacr/files/private/Update_Credential_1c.xml
<?xml version="1.0" encoding="UTF-8"?><Message xmlns="http://www.zurich.ibm.com/security/idemix" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.zurich.ibm.com/security/idemix ../xsd/Message.xsd">
  <Values>
    <Value name="capA">4577203370457028103328464524009908407678530932702268969604921740432094012057267265391467549098938756160113921075018338429871253984616919712553244267534453860570061726743969128237710056258666612030637074181673648718547405470833959238541335822229329923258603946007812460664815016752977751870583672112219685670</Value>
    <Value name="vPrimePrime">1886712313377576902346742514526196255042662312355169165251575149544895673976790723668240852236092149474250307356517605719189157119239287954840638728486234075734061720039235959124433454572765281941024178385564390868300841092367043890945209756785232283556359676415160005552358029231439914681009571746269819251508424421759021745704115780932593233202154932292394190442326451304812227409891002905779720574323004672371566909587770338305</Value>
    <Value name="e">259344723055062059907025491480697571938277889515152306249728583105665800713306759149981690559193987143066508365305231362110587327836295793570784667053393280624077323010434407507031</Value>
  </Values>
  <IdmxProof>
    <Challenge>23255962444193354344946910620481830875329124423916525451458135000974000386586</Challenge>
    <CommonValues/>
    <Values>
      <Value key="s_e" type="BigInteger">27429966007171229224226308091798167765797209766178566648184671568036522919183782340091848214987095370524832799317164070272926740957198523296915069968964482070075595000015854182032680901725029814988513733375903373223520296803913662172287245844061416356472554626697180745371107467129366265642665283614895863668</Value>
    </Values>
    <TValues/>
    <VerifiableEncryptions/>
  </IdmxProof>
  <Counter>0</Counter>
</Message>

=== lamductan/dblacr/files/private/ai_iv_message_1.xml
<?xml version="1.0" encoding="UTF-8"?><Message xmlns="http://www.zurich.ibm.com/security/idemix" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.zurich.ibm.com/security/idemix ../xsd/Message.xsd">
  <Values>
    <Value name="nonce">1738320866966628215495</Value>
  </Values>
  <IdmxProof>
    <Challenge>1337</Challenge>
    <SmartcardNonce>AAABA4CBAAA=</SmartcardNonce>
    <CommonValues>
      <CommonValue key="gp">78485280485625733211402793534323449321117898710088543846747559831834759431000</CommonValue>
      <CommonValue key="proofSpecHash">57126760908900413522883942697884168772627305488141292388350681614281959751694</CommonValue>
      <CommonValue key="sp">19313454934015494502853372660485364277088851954979011267331898025266929871326</CommonValue>
      <CommonValue key="toBeIssued">1622329355377182628938982897654668579722678911194097865043206032547496011830870885038307240606498737152264770306667168953361162400625020274170013021833054898099426777835623948380162442558603098527835398595249877258493066058088513087726781752150663236127315286193859395348348843756358438307329593536167430105</CommonValue>
      <CommonValue key="toBeIssued;issuerPk">36208523169489658024847489255733158291125038638410703786015367110824921513092</CommonValue>
    </CommonValues>
    <Values>
      <Value key="smartcard_secret;nameOfSecret" type="BigInteger">1788176471760</Value>
      <Value key="id2" type="BigInteger">2000</Value>
      <Value key="id1" type="BigInteger">1000</Value>
      <Value key="id6" type="BigInteger">14134462673820475145873042368138791195767726747297512372046077174548130664393044139834278059429705167907779833146431091933473408264124186372799513377972874003644298773301330399</Value>
      <Value key="id4" type="BigInteger">35651001231903289640854876363647492058136551834323994950127017959976402169957243653052877048230089982564652073252980360598641751735136797006629374221884283045272672627504557258</Value>
      <Value key="toBeIssued" type="BigInteger">-1317940564176786340079984120999970631353398616621967000951335292587578823710698294326523362278355634527111880866714879196896041497243663878917332688353777738768789074088583236284881075450129753487598610197483368606876632313409057051210929157401793997783623329875495714893354642618887187595935770294384485654308329747196152018696214956580872411797854962580555824906439335094216952913795242916190785057524549573751292926964160971832637</Value>
    </Values>
    <TValues>
      <TValue>63949348182483068346172876816447946740866627240923650405141273755379447734617186518275873599144142568990435103758323750191609011285507573900008601048038384662571047326560025951260756919195027789398119250533411898664527998939303691512297942509016519109214155261784862673082162380378582049165240696299672619135</TValue>
    </TValues>
    <VerifiableEncryptions/>
  </IdmxProof>
  <Counter>1</Counter>
</Message>
