=== lamductan/dblacr/files/xsd/ProofSpecification.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.zurich.ibm.com/security/idemix" xmlns="http://www.zurich.ibm.com/security/idemix"
	elementFormDefault="qualified">

	<xs:element name="ProofSpecification">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Declaration" type="DeclarationType" />
				<xs:element name="Specification" type="SpecificationType" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="DeclarationType">
		<xs:sequence>
			<xs:element name="AttributeId" type="AttributeIdType"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="AttributeIdType">
		<xs:attribute name="name" type="NonEmptyStringType" use="required" />
		<xs:attribute name="proofMode" type="proofModeType" use="required" />
		<xs:attribute name="type" type="dataType" use="required" />
	</xs:complexType>

	<xs:simpleType name="NonEmptyStringType">
		<xs:restriction base="xs:string">
			<xs:minLength value="1" />
			<xs:whiteSpace value="collapse" />
		</xs:restriction>
	</xs:simpleType>
    <xs:simpleType name="NonEmptyUriType">
        <xs:restriction base="xs:anyURI">
            <xs:minLength value="1" />
            <xs:whiteSpace value="collapse" />
        </xs:restriction>
    </xs:simpleType>

	<xs:simpleType name="proofModeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="unrevealed" />
			<xs:enumeration value="revealed" />
			<xs:enumeration value="commitment" />
			<xs:enumeration value="verenc" />
			<xs:enumeration value="nym" />
			<xs:enumeration value="message" />
		</xs:restriction>
	</xs:simpleType>

	<!-- remove and import from credential structure -->
	<xs:simpleType name="dataType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="int" />
			<xs:enumeration value="string" />
			<xs:enumeration value="epoch" />
			<xs:enumeration value="enum" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="SpecificationType">
		<xs:sequence>
			<xs:element name="Credentials" type="CredentialsType" />
            <xs:element name="CredentialCommitments" type="CredentialCommitmentsType" minOccurs="0"/>
			<xs:element name="EnumAttributes" type="EnumAttributesType" />
			<xs:element name="Inequalities" type="InequalitiesType" />
			<xs:element name="Commitments" type="CommitmentsType" />
			<xs:element name="Representations" type="RepresentationsType" />
			<xs:element name="Pseudonyms" type="PseudonymsType" />
			<xs:element name="VerifiableEncryptions" type="VerifiableEncryptionsType" />
			<xs:element name="Messages" type="MessagesType" />
            <xs:element name="Accumulators" type="AccumulatorsType" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="CredentialsType">
		<xs:sequence>
			<xs:element name="Credential" type="CredentialType"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
  
    <xs:complexType name="CredentialCommitmentsType">
        <xs:sequence>
            <xs:element name="CredentialCommitment" type="CredentialType"
                minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

	<xs:complexType name="CredentialType">
		<xs:sequence>
			<xs:element name="Attribute" type="AttributeType"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
        <xs:attribute name="issuerPublicKey" type="xs:anyURI" use="required"/>
		<xs:attribute name="credStruct" type="xs:anyURI" use="required" />
		<xs:attribute name="name" type="NonEmptyStringType" use="required" />
        <xs:attribute name="secretName" type="NonEmptyStringType" use="optional" />
	</xs:complexType>

	<xs:complexType name="AttributeType">
		<xs:simpleContent>
			<xs:extension base="NonEmptyStringType">
				<xs:attribute name="name" type="NonEmptyStringType"
					use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="EnumAttributesType">
		<xs:sequence>
			<xs:element name="EnumAttribute" type="EnumAttributeType"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="EnumAttributeType">
		<xs:sequence>
			<xs:element name="EnumValue" type="EnumValueType"
				maxOccurs="unbounded" />
			<!-- <xs:element ref="Constant" minOccurs="0" maxOccurs="unbounded" /> -->
		</xs:sequence>
		<xs:attribute name="attributeId" type="NonEmptyStringType"
			use="required" />
		<xs:attribute name="operator" type="EnumOperatorType"
			use="required" />
	</xs:complexType>

	<xs:simpleType name="EnumOperatorType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="and" />
			<xs:enumeration value="or" />
			<xs:enumeration value="not" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="EnumValueType">
		<xs:simpleContent>
			<xs:extension base="NonEmptyStringType">
				<xs:attribute name="attributeName" type="NonEmptyStringType"
					use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="InequalitiesType">
		<xs:sequence>
			<xs:element name="Inequality" type="InequalityType"
				minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="NotEqual" type="NotEqualType"
                minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="InequalityType">
		<xs:simpleContent>
			<xs:extension base="NonEmptyStringType">
				<xs:attribute name="publicKey" type="xs:anyURI" use="required" />
				<xs:attribute name="operator" type="InequalityOperatorType"
					use="required" />
				<xs:attribute name="secondArgument" type="NonEmptyStringType"
					use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
  
    <xs:complexType name="NotEqualType">
        <xs:simpleContent>
            <xs:extension base="NonEmptyStringType">
                <xs:attribute name="secondArgument" type="NonEmptyStringType" use="required" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

	<xs:simpleType name="InequalityOperatorType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="gt"></xs:enumeration>
			<xs:enumeration value="geq"></xs:enumeration>
			<xs:enumeration value="leq"></xs:enumeration>
			<xs:enumeration value="lt"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="BigIntegerType">
		<xs:restriction base="xs:string">
			<xs:whiteSpace value="collapse" />
			<xs:pattern value="-?[0-9]+" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="CommitmentsType">
		<xs:sequence>
			<xs:element name="Commitment" type="CommitmentType"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="CommitmentType">
		<xs:sequence>
			<xs:element name="Exponent" type="CommitmentExponentType"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="name" type="NonEmptyStringType" use="required" />
	</xs:complexType>

	<xs:complexType name="CommitmentExponentType">
		<xs:simpleContent>
			<xs:extension base="NonEmptyStringType">
				<xs:attribute name="index" type="xs:nonNegativeInteger"
					use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="RepresentationsType">
		<xs:sequence>
			<xs:element name="Representation" type="RepresentationType"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="RepresentationType">
		<xs:sequence>
			<xs:element name="Exponent" type="RepresentationExponentType"
				minOccurs="0" maxOccurs="unbounded" />
			<!-- <xs:element ref="Constant" minOccurs="0" maxOccurs="unbounded" /> -->
		</xs:sequence>
		<xs:attribute name="name" type="NonEmptyStringType" use="required" />
	</xs:complexType>

	<xs:complexType name="RepresentationExponentType">
		<xs:simpleContent>
			<xs:extension base="NonEmptyStringType">
				<xs:attribute name="index" type="xs:nonNegativeInteger"
					use="required" />
				<xs:attribute name="base" type="BigIntegerType" use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="PseudonymsType">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="Pseudonym" type="PseudonymType" />
			<xs:element name="DomainPseudonym" type="DomainPseudonymType" />
		</xs:choice>
        <xs:attribute name="groupParameters" type="NonEmptyStringType" use="optional"/>
	</xs:complexType>

	<xs:complexType name="PseudonymType">
		<xs:attribute name="name" type="NonEmptyStringType" use="required"/>
        <xs:attribute name="secretName" type="NonEmptyStringType" use="required"/>
	</xs:complexType>
  
    <xs:complexType name="DomainPseudonymType">
        <xs:attribute name="name" type="NonEmptyStringType" use="required"/>
        <xs:attribute name="scope" type="NonEmptyUriType" use="required"/>
        <xs:attribute name="secretName" type="NonEmptyStringType" use="required"/>
    </xs:complexType>

	<xs:complexType name="VerifiableEncryptionsType">
		<xs:sequence>
			<xs:element name="VerifiableEncryption" type="VerifiableEncryptionType"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="VerifiableEncryptionType">
		<xs:simpleContent>
			<xs:extension base="NonEmptyStringType">
				<xs:attribute name="name" type="NonEmptyStringType"
					use="required" />
				<xs:attribute name="publicKey" type="xs:anyURI" use="required" />
				<xs:attribute name="label" type="NonEmptyStringType"
					use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="MessagesType">
		<xs:sequence>
			<xs:element name="Message" type="MessageType" minOccurs="0"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
  
    <xs:complexType name="AccumulatorsType">
        <xs:sequence>
            <xs:element name="Accumulator" type="AccumulatorType" minOccurs="0"
                maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="AccumulatorType">
      <xs:simpleContent>
        <xs:extension base="NonEmptyStringType">
          <xs:attribute name="name" type="NonEmptyStringType" use="required"/>
          <xs:attribute name="publicKey" type="NonEmptyStringType" use="required"/>
          <xs:attribute name="epoch" type="xs:integer" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>

	<xs:complexType name="MessageType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="name" type="NonEmptyStringType" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

</xs:schema>

=== lamductan/dblacr/files/proofSpecifications/ProofSpecMessage_Cred2Cred3.xml
<?xml version="1.0" encoding="UTF-8"?>
<ProofSpecification xmlns="http://www.zurich.ibm.com/security/idemix"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.zurich.ibm.com/security/idemix ../xsd/ProofSpecification.xsd">

	<Declaration>
		<AttributeId name="id1" proofMode="unrevealed" type="int" />
		<AttributeId name="id2" proofMode="unrevealed" type="int" />
		<AttributeId name="id3" proofMode="unrevealed" type="int" />
		<AttributeId name="id4" proofMode="unrevealed" type="int" />
		<AttributeId name="id5" proofMode="unrevealed" type="int" />
		<AttributeId name="id6" proofMode="unrevealed" type="int" />
	</Declaration>

	<Specification>
		<Credentials>
			<Credential issuerPublicKey="http://www.issuer.com/ipk.xml"
				credStruct="http://www.ngo.org/CredStruct2.xml" name="someRandomNameMatchingTheOneInTheProofSpec">
				<Attribute name="attr1">id4</Attribute>
				<Attribute name="attr2">id3</Attribute>
				<Attribute name="attr3">id2</Attribute>
				<Attribute name="attr4">id1</Attribute>
				<Attribute name="attr5">id5</Attribute>
				<Attribute name="attr6">id6</Attribute>
			</Credential>
			<Credential issuerPublicKey="http://www.issuer.com/ipk.xml"
				credStruct="http://www.ngo.org/CredStruct3.xml" name="someRandomNameMatchingTheOneInTheProofSpec">
				<Attribute name="attr1">id2</Attribute>
				<Attribute name="attr2">id5</Attribute>
				<Attribute name="attr3">id1</Attribute>
			</Credential>
		</Credentials>

		<EnumAttributes />

		<Inequalities />

		<Commitments />

		<Representations />

		<Pseudonyms />

		<VerifiableEncryptions />

		<Messages>
			<Message name="randMessageName">This is the message we want signed. It can be
				any string.</Message>
		</Messages>

	</Specification>

</ProofSpecification>

=== lamductan/dblacr/files/proofSpecifications/ProofSpec0_pseudonym.xml
<?xml version="1.0" encoding="UTF-8"?>
<ProofSpecification xmlns="http://www.zurich.ibm.com/security/idemix"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.zurich.ibm.com/security/idemix ../xsd/ProofSpecification.xsd">

	<Declaration />


	<Specification>
		<Credentials>
			<Credential issuerPublicKey="http://www.issuer.com/ipk.xml"
				credStruct="http://www.ngo.org/CredStruct0.xml" name="someRandomName">
			</Credential>
		</Credentials>

		<EnumAttributes />

		<Inequalities />

		<Commitments />

		<Representations />

		<Pseudonyms>
			<Pseudonym name="someName" secretName="blabla"/>
		</Pseudonyms>

		<VerifiableEncryptions />

		<Messages />

	</Specification>

</ProofSpecification>

=== lamductan/dblacr/files/proofSpecifications/ProofSpecAccumulator.xml
<?xml version="1.0" encoding="UTF-8"?>
<ProofSpecification xmlns="http://www.zurich.ibm.com/security/idemix"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.zurich.ibm.com/security/idemix ../xsd/ProofSpecification.xsd">

	<Declaration>
		<AttributeId name="id1" proofMode="revealed" type="int" />
		<AttributeId name="id2" proofMode="unrevealed" type="int" />
		<AttributeId name="id3" proofMode="unrevealed" type="int" />
		<AttributeId name="id4" proofMode="unrevealed" type="int" />
	</Declaration>

	<Specification>
		<Credentials>
			<Credential issuerPublicKey="http://www.issuer.com/ipk.xml"
				credStruct="http://www.ngo.org/CredStruct1b.xml" name="someRandomName">
				<Attribute name="attr1">id1</Attribute>
				<Attribute name="attr2">id2</Attribute>
				<Attribute name="attr3">id4</Attribute>
				<Attribute name="attr4">id3</Attribute>
			</Credential>
		</Credentials>

		<EnumAttributes />

		<Inequalities />

		<Commitments />

		<Representations />

		<Pseudonyms />

		<VerifiableEncryptions />

		<Messages />
    
        <Accumulators>
          <Accumulator name="acc" publicKey="idemix://acc/pk" epoch="1">id3</Accumulator>
        </Accumulators>

	</Specification>

</ProofSpecification>

=== lamductan/dblacr/files/proofSpecifications/ProofSpecDomNymSmartcard.xml
<?xml version="1.0" encoding="UTF-8"?>
<ProofSpecification xmlns="http://www.zurich.ibm.com/security/idemix"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.zurich.ibm.com/security/idemix ../xsd/ProofSpecification.xsd"
  >

	<Declaration/>

	<Specification>
		<Credentials/>

		<EnumAttributes />

		<Inequalities />

		<Commitments />

		<Representations />

		<Pseudonyms groupParameters="http://www.zurich.ibm.com/security/idmx/v2/gp.xml">
			<DomainPseudonym name="employeeCorner" scope="http://www.zurich.ibm.com/employeeCorner" secretName="blibli" />
		</Pseudonyms>

		<VerifiableEncryptions />

		<Messages />

	</Specification>

</ProofSpecification>

=== lamductan/dblacr/files/proofSpecifications/ProofSpecInequality_Cred2.xml
<?xml version="1.0" encoding="UTF-8"?>
<ProofSpecification xmlns="http://www.zurich.ibm.com/security/idemix"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.zurich.ibm.com/security/idemix ../xsd/ProofSpecification.xsd">

	<Declaration>
		<AttributeId name="id1" proofMode="unrevealed" type="int" />
		<AttributeId name="id2" proofMode="unrevealed" type="int" />
		<AttributeId name="id3" proofMode="revealed" type="int" />
		<AttributeId name="id4" proofMode="revealed" type="int" />
		<AttributeId name="id5" proofMode="unrevealed" type="int" />
		<AttributeId name="id6" proofMode="unrevealed" type="int" />
	</Declaration>

	<Specification>
		<Credentials>
			<Credential issuerPublicKey="http://www.issuer.com/ipk.xml"
				credStruct="http://www.ngo.org/CredStruct2.xml" name="someRandomNameMatchingTheOneInTheProofSpec">
				<Attribute name="attr1">id4</Attribute>
				<Attribute name="attr2">id3</Attribute>
				<Attribute name="attr3">id2</Attribute>
				<Attribute name="attr4">id1</Attribute>
				<Attribute name="attr5">id5</Attribute>
				<Attribute name="attr6">id6</Attribute>
			</Credential>
			<Credential issuerPublicKey="http://www.issuer.com/ipk.xml"
				credStruct="http://www.ngo.org/CredStruct3.xml" name="someRandomNameMatchingTheOneInTheProofSpec">
				<Attribute name="attr1">id2</Attribute>
				<Attribute name="attr2">id5</Attribute>
				<Attribute name="attr3">id1</Attribute>
			</Credential>
		</Credentials>

		<EnumAttributes />

		<Inequalities>
			<Inequality
				publicKey="http://www.issuer.com/ipk.xml"
				operator="geq" secondArgument="1313">id1</Inequality>
			<Inequality
				publicKey="http://www.issuer.com/ipk.xml"
				operator="lt" secondArgument="1316">id1</Inequality>
			<Inequality
				publicKey="http://www.issuer.com/ipk.xml"
				operator="lt" secondArgument="23949832742">id2</Inequality>
			<Inequality
				publicKey="http://www.issuer.com/ipk.xml"
				operator="gt" secondArgument="-328428374921315">id2</Inequality>
			<Inequality
				publicKey="http://www.issuer.com/ipk.xml"
				operator="lt" secondArgument="8293">id2</Inequality>
			<Inequality
				publicKey="http://www.issuer.com/ipk.xml"
				operator="gt" secondArgument="29">id2</Inequality>
			<Inequality
				publicKey="http://www.issuer.com/ipk.xml"
				operator="lt" secondArgument="92803492834023804238">id5</Inequality>
			<Inequality
				publicKey="http://www.issuer.com/ipk.xml"
				operator="leq" secondArgument="1317">id5</Inequality>
			<Inequality
				publicKey="http://www.issuer.com/ipk.xml"
				operator="geq" secondArgument="1317">id5</Inequality>
			<Inequality
				publicKey="http://www.issuer.com/ipk.xml"
				operator="geq" secondArgument="id4">id5</Inequality>
			<Inequality
				publicKey="http://www.issuer.com/ipk.xml"
				operator="lt" secondArgument="id3">id2</Inequality>
            <NotEqual secondArgument="1313">id2</NotEqual>
            <NotEqual secondArgument="1315">id2</NotEqual>
            <NotEqual secondArgument="0">id2</NotEqual>
            <NotEqual secondArgument="999999999999999999999999999999999999999999999">id2</NotEqual>
            <NotEqual secondArgument="id4">id2</NotEqual>
            <NotEqual secondArgument="id3">id4</NotEqual>
            <NotEqual secondArgument="42">id4</NotEqual>
		</Inequalities>

		<Commitments />

		<Representations />

		<Pseudonyms />

		<VerifiableEncryptions />

		<Messages />

	</Specification>

</ProofSpecification>

=== lamductan/dblacr/files/proofSpecifications/ProofSpec2.xml
<?xml version="1.0" encoding="UTF-8"?>
<ProofSpecification xmlns="http://www.zurich.ibm.com/security/idemix"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.zurich.ibm.com/security/idemix ../xsd/ProofSpecification.xsd">

	<Declaration>
		<AttributeId name="id1" proofMode="unrevealed" type="int" />
		<AttributeId name="id2" proofMode="revealed" type="int" />
		<AttributeId name="id3" proofMode="unrevealed" type="int" />
		<AttributeId name="id4" proofMode="revealed" type="int" />
		<AttributeId name="id5" proofMode="unrevealed" type="int" />
		<AttributeId name="id6" proofMode="revealed" type="int" />
	</Declaration>

	<Specification>
		<Credentials>
			<Credential issuerPublicKey="http://www.issuer.com/ipk.xml"
				credStruct="http://www.ngo.org/CredStruct2.xml" name="someRandomNameMatchingTheOneInTheProofSpec">
				<Attribute name="attr1">id1</Attribute>
				<Attribute name="attr2">id2</Attribute>
				<Attribute name="attr3">id4</Attribute>
				<Attribute name="attr4">id6</Attribute>
				<Attribute name="attr5">id5</Attribute>
				<Attribute name="attr6">id3</Attribute>
			</Credential>
		</Credentials>

		<EnumAttributes />

		<Inequalities />

		<Commitments />

		<Representations />

		<Pseudonyms />

		<VerifiableEncryptions />

		<Messages />

	</Specification>

</ProofSpecification>

=== lamductan/dblacr/files/proofSpecifications/ProofSpecAdvancedIssuanceScNoUser.xml
<?xml version="1.0" encoding="UTF-8"?>
<ProofSpecification xmlns="http://www.zurich.ibm.com/security/idemix"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.zurich.ibm.com/security/idemix ../xsd/ProofSpecification.xsd">

	<Declaration>
	</Declaration>

	<Specification>
		<Credentials />
    
        <CredentialCommitments>
          <CredentialCommitment issuerPublicKey="http://www.issuer.com/ipk.xml"
                  credStruct="http://www.ngo.org/CredStructWithSmartcardNoUser.xml"
                  name="toBeIssued"
                  secretName="nameOfSecret">
          </CredentialCommitment>
        </CredentialCommitments>

		<EnumAttributes />

		<Inequalities />

		<Commitments />

		<Representations />

		<Pseudonyms />

		<VerifiableEncryptions />

		<Messages />

	</Specification>

</ProofSpecification>

=== lamductan/dblacr/files/proofSpecifications/ProofSpec1d.xml
<?xml version="1.0" encoding="UTF-8"?>
<ProofSpecification xmlns="http://www.zurich.ibm.com/security/idemix"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.zurich.ibm.com/security/idemix ../xsd/ProofSpecification.xsd">

	<Declaration>
		<AttributeId name="id1" proofMode="revealed" type="int" />
		<AttributeId name="id2" proofMode="unrevealed" type="string" />
		<AttributeId name="id3" proofMode="unrevealed" type="int" />
		<AttributeId name="id4" proofMode="unrevealed" type="epoch" />
	</Declaration>

	<Specification>
		<Credentials>
			<Credential issuerPublicKey="http://www.issuer.com/ipk.xml"
				credStruct="http://www.ngo.org/CredStruct1d.xml"
				name="someRandomName"
				>
				<Attribute name="attr1">id1</Attribute>
				<Attribute name="attr2">id2</Attribute>
				<Attribute name="attr3">id3</Attribute>
				<Attribute name="attr4">id4</Attribute>
			</Credential>
		</Credentials>

		<EnumAttributes />

		<Inequalities>
			<Inequality
				publicKey="http://www.issuer.com/ipk.xml"
				operator="geq" secondArgument="CURRENT_EPOCH">id4</Inequality>
		</Inequalities>

		<Commitments />

		<Representations />

		<Pseudonyms />

		<VerifiableEncryptions />

		<Messages />

	</Specification>

</ProofSpecification>
