=== lamductan/dblacr/files/xsd/SystemParameters.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema 
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.zurich.ibm.com/security/idemix"
	xmlns="http://www.zurich.ibm.com/security/idemix"
	elementFormDefault="qualified">
  
  <xs:element name="Elements" type="ElementsType" />
    
  <xs:element name="SystemParameters">
    <xs:complexType>
    <xs:sequence>
      <xs:element name="Elements" type="ElementsType" />
    </xs:sequence>
  </xs:complexType>
  </xs:element>
  
  <xs:complexType name="ElementsType">
    <xs:all>
      <xs:element name="l_e" type="xs:positiveInteger" />
      <xs:element name="l_ePrime" type="xs:positiveInteger" />
      <xs:element name="l_Gamma" type="xs:positiveInteger" />
      <xs:element name="l_H" type="xs:positiveInteger" />
      <xs:element name="l_k" type="xs:positiveInteger" />
      <xs:element name="l_m" type="xs:positiveInteger" />
      <xs:element name="l_n" type="xs:positiveInteger" />
      <xs:element name="l_Phi" type="xs:positiveInteger" />
      <xs:element name="l_pt" type="xs:positiveInteger" />
      <xs:element name="l_r" type="xs:positiveInteger" />
      <xs:element name="l_res" type="xs:positiveInteger" />
      <xs:element name="l_rho" type="xs:positiveInteger" />
      <xs:element name="l_v" type="xs:positiveInteger" />
      <xs:element name="l_enc" type="xs:positiveInteger" />
    </xs:all>
  </xs:complexType>

</xs:schema>

=== lamductan/dblacr/files/parameter/sp.xml
<?xml version="1.0" encoding="UTF-8"?>
<SystemParameters xmlns="http://www.zurich.ibm.com/security/idemix"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xsi:schemaLocation="http://www.zurich.ibm.com/security/idemix ../xsd/SystemParameters.xsd">
	

    <Elements>
        <l_e>597</l_e>
        <l_ePrime>257</l_ePrime>
        <l_Gamma>1024</l_Gamma>
        <l_H>256</l_H>
        <l_k>144</l_k>
        <l_m>256</l_m>
        <l_n>1024</l_n>
        <l_Phi>72</l_Phi>
        <l_pt>72</l_pt>
        <l_r>72</l_r>
        <l_res>1</l_res>
        <l_rho>256</l_rho>
        <l_v>1427</l_v>
        <l_enc>256</l_enc>
    </Elements>

       <!-- 
         <Elements>
        <l_e>621</l_e>
        <l_ePrime>257</l_ePrime>
        <l_Gamma>2048</l_Gamma>
        <l_H>256</l_H>
        <l_k>208</l_k>
        <l_m>256</l_m>
        <l_n>2048</l_n>
        <l_Phi>104</l_Phi>
        <l_pt>104</l_pt>
        <l_r>104</l_r>
        <l_res>1</l_res>
        <l_rho>256</l_rho>
        <l_v>2515</l_v>
        <l_enc>256</l_enc> 
    </Elements>-->
</SystemParameters>
