=== lamductan/dblacr/files/xsd/VerifiableEncryptionPublicKey.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema 
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.zurich.ibm.com/security/idemix"
	xmlns="http://www.zurich.ibm.com/security/idemix"
	elementFormDefault="qualified">
  
  <xs:element name="VerifiableEncryptionPublicKey">
  	<xs:complexType>
  		<xs:all>
  			<xs:element name="References" type="ReferencesType" />
  			<xs:element name="Elements" type="ElementsType" />
  		</xs:all>
  	</xs:complexType>
  </xs:element>
  
  <xs:complexType name="ReferencesType">
  	<xs:all>
  		<xs:element name="SystemParameters" type="xs:anyURI" />
  	</xs:all>
  </xs:complexType>
  
  <xs:complexType name="ElementsType">
  	<xs:all>
  		<xs:element name="g" type="BigIntegerType" />
  		<xs:element name="n" type="BigIntegerType" />
  		<xs:element name="y1" type="BigIntegerType" />
  		<xs:element name="y2" type="BigIntegerType" />
  		<xs:element name="y3" type="BigIntegerType" />
  	</xs:all>
  </xs:complexType>

  <xs:simpleType name="BigIntegerType">
  	<xs:restriction base="xs:string">
  		<xs:whiteSpace value="collapse" />
  		<xs:pattern value="-?[0-9]+" />
    </xs:restriction>
  </xs:simpleType>
  
</xs:schema>

=== lamductan/dblacr/files/testTrustedParty/vepk.xml
<?xml version="1.0" encoding="UTF-8"?><VerifiableEncryptionPublicKey xmlns="http://www.zurich.ibm.com/security/idemix" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.zurich.ibm.com/security/idemix ../xsd/VerifiableEncryptionPublicKey.xsd">
  <References>
    <SystemParameters>http://www.zurich.ibm.com/security/idmx/v2/sp.xml</SystemParameters>
  </References>
  <Elements>
    <g>9194327137339830968541009746742966200739125995065968640987631527918276195692845371843886348226542548410717447375818041418951779443786628732488736478939065398326480932766053021601613695076728535326207510456766859152644277957066298469764251001698706792316485281115685033801190236285198727523164509250260048449395338751213389557254832087480376417847063841015268802362359384762197836473833129923147021561676548935435375803381664911694451035327480606540226723627161386893258000366518830128953914476862256868325911484559691332842769605058276790695271914512113781710323260948325276771208345341391936621823716442707726775995</g>
    <n>125601958664822213718986585970328691765155661651401034838888652085535193921078187752765494575740107057678898006932649673613622251545024452399247863317163640271778454787749153876124425339768764145999843732799198860700905350168751367455905768396696191810766426097656504594814784854735240814674529034236020558089</n>
    <y1>12239818305906692826179214763743341996706046077260561198408384411706981611097338178550874627741105475213603992753446969448136863935807871936389000527110144287608780941417629838014415742599738356516800872895688596158421855122544495499839810828249413009558129815614941793965272397323454343319389958258799620413073032207474450525794959274117902959099690962576951025896812793637187685744855311972609372837617586629360300662415579045341939686491554473460960775544102445419144220535311948416924242952424495845332992370975542083675400969044537394639414212146797713865058539326297527090214751707532099245835839309165847160132</y1>
    <y2>3750661151120060227058719337565736608353372314986463854768162868035162476547227280162737518792335608126911019746092732322632480203852402095643495761036823955730149585140342355129794157881529481248836382275229632052008469722270434295133628306886923363750168181648156167783707449609926266004890750287722062813086571428136424611562625113380073648156853608057568699355125340225261659587060118379739464416537132230618964156337607300010788635899350868632620410140265120804626655122334282212660641012362768359893835756149042981064713607797387365278571875644818546458483221664633110118324229540799654634948648810957719163253</y2>
    <y3>2902590412654866663425311921630313039564439258022055660228307746716702725246147969227687653386124599214491951662447728751612014660603054999466227824937266727138283404424200679668990543222043352984700832700460699747692459983112339751134807923583014148753040547870341070092947783526816222765075494542888469261772153224641784202579692565311829692624745302231698248063798700930758523845074087619807144366032464394664203998650459366837265395713536868303112389036818299748543490851973477768923578481182985430633901331403316263204765330509163379134878933240485244387275738849942772393821474581749895636364459052674468488299</y3>
  </Elements>
</VerifiableEncryptionPublicKey>
