=== lamductan/dblacr/files/xsd/VerifiableEncryption.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://www.zurich.ibm.com/security/idemix" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:idemix="http://www.zurich.ibm.com/security/idemix">
  <xs:element name="VerifiableEncryption">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="idemix:Locations"/>
        <xs:element ref="idemix:Elements"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Locations">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="idemix:VEPublicKeyLocation"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="VEPublicKeyLocation" type="xs:anyURI"/>
  <xs:element name="Elements">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="idemix:Label"/>
        <xs:element ref="idemix:u"/>
        <xs:element ref="idemix:e"/>
        <xs:element ref="idemix:v"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Label" type="xs:integer"/>
  <xs:element name="u" type="xs:integer"/>
  <xs:element name="e" type="xs:integer"/>
  <xs:element name="v" type="xs:integer"/>
</xs:schema>

=== lamductan/dblacr/files/testTrustedParty/ve1_verifier.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<VerifiableEncryption xmlns="http://www.zurich.ibm.com/security/idemix" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.zurich.ibm.com/security/idemix ../xsd/VerifiableEncryption.xsd">
  <Locations>
    <VEPublicKeyLocation>http://www.un.org/vepk.xml</VEPublicKeyLocation>
  </Locations>
  <Elements>
    <Label>8405871848956469194822056536482389885716323069902230794807375833616346732721</Label>
    <u>15275813926637195941293146757107001824632991753188736897791498900086430470599721275119953215118737500015607449353639717439525466697561805030215835057771836465320146248307006018512797098682054038030031828904512103634657009453841625633871295385612877839770582150760159854588664605947397363854468748443210893196341714275891679689068950997536100115944749295359485193427165709170691012112162538405862056479673827090510157622918415050420990528158633861495388584149984213383913716440825079217104621181769537571793570100400286977031778992902777526984203165836963009919157354766949827358707640292082504665175244274586327821030</u>
    <e>2828284664319855904400173178867746369810064758676488085355986874752061776826479362943620282903039212097995459513644022562396124514730370479293521497680166528298093495734112314243166466709177279003657236595407844383842571140870463742455164580785502480703328904787032071849713569651190636169325451848878941759968772778531001209509015098493766511426929459923221783840499029857131588987761506306719694096104290545670545851632880900378129927560779280957974595405153024231626147966374893343384749131635308998246168416489131222305059475629349522624454334055916304464729671365760918563928817884280359237687406405470981208703</e>
    <v>7556275116171479526928424718607532494662459738001001716017729572186143371400791542955047271122462240134515039699811600598979524594799837260705078600554288664246278452969618247425889811172496209040616916550316417098209294509171188508296536763142714853576092084461094087206879078593437961628254558407166188388715655465392813651007426097021025589413471742607407234087552378889825885477924611341909733987593924365728221235148852098657227537320233323699541768047689682650860332331769756382450557328706316785156502548506535281028215576934019764451306765947020097104222232496841415692417537252619157065195264857205009482170</v>
  </Elements>
</VerifiableEncryption>
