=== lamductan/dblacr/files/xsd/VerifiableEncryptionPrivateKey.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema 
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.zurich.ibm.com/security/idemix"
	xmlns="http://www.zurich.ibm.com/security/idemix"
	elementFormDefault="qualified">
  
  <xs:element name="VerifiableEncryptionPrivateKey">
  	<xs:complexType>
  		<xs:all>
  			<xs:element name="References" type="ReferencesType" />
  			<xs:element name="Elements" type="ElementsType" />
  		</xs:all>
  	</xs:complexType>
  </xs:element>
  
  <xs:complexType name="ReferencesType">
  	<xs:all>
  		<xs:element name="VerifiableEncryptionPublicKey" type="xs:anyURI" />
  	</xs:all>
  </xs:complexType>
  
  <xs:complexType name="ElementsType">
  	<xs:all>
  		<xs:element name="orderN" type="BigInteger" />
  		<xs:element name="x1" type="BigInteger" />
  		<xs:element name="x2" type="BigInteger" />
  		<xs:element name="x3" type="BigInteger" />
  	</xs:all>
  </xs:complexType>

  <xs:simpleType name="BigInteger">
  	<xs:restriction base="xs:string">
  		<xs:whiteSpace value="collapse" />
  		<xs:pattern value="[0-9]+" />  	
    </xs:restriction>
  </xs:simpleType>
  
</xs:schema>

=== lamductan/dblacr/files/private/vesk.xml
<?xml version="1.0" encoding="UTF-8"?><VerifiableEncryptionPrivateKey xmlns="http://www.zurich.ibm.com/security/idemix" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.zurich.ibm.com/security/idemix ../xsd/VerifiableEncryptionPrivateKey.xsd">
  <References>
    <VerifiableEncryptionPublicKey>http://www.un.org/vepk.xml</VerifiableEncryptionPublicKey>
  </References>
  <Elements>
    <orderN>125601958664822213718986585970328691765155661651401034838888652085535193921078187752765494575740107057678898006932649673613622251545024452399247863317163617857055308631198823853178447691948548617100347170489013668499570245323781991449599212317381717749466409530471708279589115539815435245479311241932084734724</orderN>
    <x1>1575619408618685535637543243543308131613169042910853496150316322419616192999995276075964093510355275951270504150830111557034983073005991266618989537756329642666806594733352842236665419144067786354847495418547383553938600714673865204039154518398617246152869656199063848410011963962879100114316540576495075114788168240356679072490603055450709700382534559378884859818464512187593311890408792113290494840689744031823315058385638953561756017941987294967401699117456450982538999717265209828774181284737159016342335901061426001248081628029565480791231699736900148550531546445103407726336901428823101472095109871099823264689</x1>
    <x2>1861261694444416577078237266364990021497717970963109018088691886690760611057687496666846870929496722610972553290276145025448207259438514364305863225903362759308985624985575005140397294358921577442272262823138496861408031112552906679654411598425659235804462294095554681976848064928815943542171273815831048407460829716840564559087004116047728066030053126943030439117417740749249093420464821936719144407325022214394965634246050005360819195972726282269085285442813677768098534922268896313615746591327534767469140210686442418070531348824949906501991691790767066026012065258204035983951854137047436222851450067361333378664</x2>
    <x3>1854558355827427121617701167446065637528316527747136359037662355944487087577103817682502337934226607230945692435164775251725534409963140623019373375134425627929069216522141834481601608346406836271777149246751693607334293146807096267319342053409579982314101022801740728184821394349014371730456744249168004414758811073031687886818536764764429098100481118387079776424611297202435555070685048229434487900507839169571729719288443201035388256546555027029308464176336872423822820466960434058957044590109285734818710802726758559967257048218384051056703977562355846295381598076306578366840892417440792389533359767233067507474</x3>
  </Elements>
</VerifiableEncryptionPrivateKey>
